import { constantLocationData } from "../../constant-mock-data/constantLocationData.mock"
import { constantOperatoryData, constantProviderBlock, constantOperatoryOptoData, constantProvidersDentalData } from "../../constant-mock-data/constantOperatoryData.mock";

const locationTimezone = {
    "_id": constantLocationData.austin.id,
    "name": "Saskatchewan",
    "zone": "Canada/Saskatchewan",
    "gmt": "(GMT-06:00)",
    "alias": "saskatchewan",
    "is_active": true,
    "created_at": 1550131715928,
    "updated_at": 1550131715928,
    "deleted_at": null
}

const locationFields = Object.entries(constantLocationData).reduce(
    (acc, [key, loc]) => {
        acc[key] = {
            location: { application_name: "Eaglesoft", $id: loc.id, location: { $ref: "location", $id: loc.id }, },
            appointmentlocationId: loc.id,
            appointmentlocationName: loc.name,
        };
        return acc;
    },
    {} as Record<keyof typeof constantLocationData,
        { location: { application_name: string; $id: string; location: { $ref: string; $id: string } }; appointmentlocationId: string; appointmentlocationName: string; }>
);

const apptsBase = {
    dental: {
        MileySmiley: {
            "first_name": "Miley",
            "last_name": "Smiley",
            "email": "miley.smiley@gmail.com",
            "mobile": "8326040145",
            "comment": "",
            "homephone": "",
            "appt_ehr_id": "332",
            "appointment_status": "complete",
            "appointment_status_ehr_key": "444",
            "confirmed_status_ehr_key": "444",
            "finalstatus": "complete",
            "unschedule_status": "",
            "confirmed_status": "complete",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "appointmenttype": { "name": "New Patient Exam DR" },
            "engage": true,
            "pozative": true,
            "procedurecode": "T3542, D0274, D2392, N1254",
            "proceduredesc": "Composite-4 Surf, Anterior or More Surfaces, D0274, D2392, Watch",
            "patientId": "06dental-a123-b456-c789-d101112e1306",
            ...locationFields.austin,
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
        RuthCanal: {
            "first_name": "Ruth",
            "last_name": "Canal",
            "email": "ruth.canal@gmail.com",
            "mobile": "8326506958",
            "comment": "",
            "homephone": "",
            "appt_ehr_id": "333",
            "appointment_status": "schedule",
            "appointment_status_ehr_key": "111",
            "confirmed_status_ehr_key": "111",
            "finalstatus": "confirmed",
            "unschedule_status": "",
            "confirmed_status": "not called",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "appointmenttype": { "name": "New Patient Exam DR" },
            "engage": true,
            "pozative": true,
            "procedurecode": "T6452, T6462, T6472",
            "proceduredesc": "Post & Core, Root Canal, Root Canal",
            "patientId": "01dental-a123-b456-c789-d101112e1301",
            ...locationFields.austin,
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
        EveNamel: {
            "first_name": "Eve",
            "last_name": "Namel",
            "email": "eve.namel@gmail.com",
            "mobile": "9988776655",
            "comment": "",
            "homephone": "2027953213",
            "appt_ehr_id": "334",
            "appointment_status": "unconfirmed",
            "appointment_status_ehr_key": "333",
            "confirmed_status_ehr_key": "333",
            "finalstatus": "unconfirmed",
            "unschedule_status": "",
            "confirmed_status": "appointment confirmed",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "appointmenttype": { "name": "New Patient Exam DR" },
            "engage": true,
            "pozative": true,
            "procedurecode": "T7966, T5843, D4342, T1546",
            "proceduredesc": "Root Canal, Bicuspid, Composite-3 Surf, Posterior, D4342, Intraoral Periapical Film",
            "patientId": "02dental-a123-b456-c789-d101112e1302",
            ...locationFields.austin,
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
        PerryODontist: {
            "first_name": "Perry",
            "last_name": "O'Dontist",
            "email": "perry.o.dontist@gmail.com",
            "mobile": "1122334455",
            "comment": "",
            "homephone": "",
            "appt_ehr_id": "336",
            "appointment_status": "missed",
            "appointment_status_ehr_key": "222",
            "confirmed_status_ehr_key": "222",
            "finalstatus": "missed",
            "unschedule_status": "",
            "confirmed_status": "appointment missed",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "appointmenttype": { "name": "New Patient Exam DR" },
            "engage": true,
            "pozative": true,
            "procedurecode": "T3522, T5833, T6245, T6255",
            "proceduredesc": "Composite-2 Surf, Anterior, Composite-2 Surf, Posterior, Bridge Pontic, PFM, Bridge Retainer, PFM",
            "patientId": "04dental-a123-b456-c789-d101112e1304",
            ...locationFields.austin,
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
    },
    optometry: {
        ImaSeewell: {
            "first_name": "Ima",
            "last_name": "Seewell",
            "email": "ima.seewell@gmail.com",
            "mobile": "8326040145",
            "comment": "",
            "homephone": "",
            "appt_ehr_id": "332",
            "appointment_status": "complete",
            "appointment_status_ehr_key": "444",
            "confirmed_status_ehr_key": "444",
            "finalstatus": "complete",
            "unschedule_status": "",
            "confirmed_status": "not called",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "appointmenttype": { "name": "New Patient Exam DR" },
            "engage": true,
            "pozative": true,
            "procedurecode": "T6452, T6462, T6472",
            "proceduredesc": "Post & Core, Root Canal, Root Canal",
            "patientId": "068e6525-opto-b456-c789-d101112e1306",
            ...locationFields.austin,
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
        CrystalClearview: {
            "first_name": "Crystal",
            "last_name": "Clearview",
            "email": "crystal.clearview@gmail.com",
            "mobile": "8326506958",
            "comment": "",
            "homephone": "",
            "appt_ehr_id": "333",
            "appointment_status": "schedule",
            "appointment_status_ehr_key": "111",
            "confirmed_status_ehr_key": "111",
            "finalstatus": "confirmed",
            "unschedule_status": "",
            "confirmed_status": "not called",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "appointmenttype": { "name": "New Patient Exam DR" },
            "engage": true,
            "pozative": true,
            "procedurecode": "T3542, D0274, D2392, N1254",
            "proceduredesc": "Composite-4 Surf, Anterior or More Surfaces, D0274, D2392, Watch",
            "patientId": "038e6525-opto-b456-c789-d101112e1303",
            ...locationFields.austin,
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
        CeeVision: {
            "first_name": "Cee",
            "last_name": "Vision",
            "email": "cee.vision@gmail.com",
            "mobile": "9988776655",
            "comment": "",
            "homephone": "2027953213",
            "appt_ehr_id": "334",
            "appointment_status": "unconfirmed",
            "appointment_status_ehr_key": "333",
            "confirmed_status_ehr_key": "333",
            "finalstatus": "unconfirmed",
            "unschedule_status": "",
            "confirmed_status": "appointment confirmed",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "appointmenttype": { "name": "New Patient Exam DR" },
            "engage": true,
            "pozative": true,
            "procedurecode": "T7966, T5843, D4342, T1546",
            "proceduredesc": "Root Canal, Bicuspid, Composite-3 Surf, Posterior, D4342, Intraoral Periapical Film",
            "patientId": "028e6525-opto-b456-c789-d101112e1302",
            ...locationFields.austin,
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
        EllieOVision: {
            "first_name": "Ellie O.",
            "last_name": "Vision",
            "email": "ellie.o.vision@gmail.com",
            "mobile": "1122334455",
            "comment": "",
            "homephone": "",
            "appt_ehr_id": "336",
            "appointment_status": "missed",
            "appointment_status_ehr_key": "222",
            "confirmed_status_ehr_key": "222",
            "finalstatus": "missed",
            "unschedule_status": "",
            "confirmed_status": "appointment confirmed",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "appointmenttype": { "name": "New Patient Exam DR" },
            "engage": true,
            "pozative": true,
            "procedurecode": "T3522, T5833, T6245, T6255",
            "proceduredesc": "Composite-2 Surf, Anterior, Composite-2 Surf, Posterior, Bridge Pontic, PFM, Bridge Retainer, PFM",
            "patientId": "048e6525-opto-b456-c789-d101112e1304",
            ...locationFields.austin,
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
    },
    chiropractor: {
        AllyVertebrae: {
            "first_name": "Ally",
            "last_name": "Vertebrae",
            "email": "ally.vertebrae@gmail.com",
            "mobile": "8326506958",
            "comment": "",
            "homephone": "",
            "appt_ehr_id": "331",
            "appointment_status": "unconfirmed",
            "appointment_status_ehr_key": "333",
            "confirmed_status_ehr_key": "333",
            "finalstatus": "unconfirmed",
            "unschedule_status": "",
            "confirmed_status": "appointment confirmed",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "provider": [constantProviderBlock.defaultProvider],
            "appointmenttype": { "name": "New Patient Exam DR" },
            ...locationFields.austin,
            "engage": true,
            "pozative": true,
            "procedurecode": "T5823, T9836",
            "proceduredesc": "Bridge Pontic, Mandibular Denture",
            "patientId": "01chirop-a123-b456-c789-d101112e1301",
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
        AnitaCrack: {
            "first_name": "Anita",
            "last_name": "Crack",
            "email": "anita.crack@gmail.com",
            "mobile": "8324897898",
            "comment": "",
            "homephone": "2027953213",
            "appt_ehr_id": "330",
            "appointment_status": "schedule",
            "appointment_status_ehr_key": "111",
            "confirmed_status_ehr_key": "111",
            "finalstatus": "confirmed",
            "unschedule_status": "",
            "confirmed_status": "not called",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "provider": [constantProviderBlock.defaultProvider],
            "appointmenttype": { "name": "New Patient Exam DR" },
            ...locationFields.austin,
            "engage": true,
            "pozative": true,
            "procedurecode": "T3512, T3532, T1254, T1632, D9986",
            "proceduredesc": "Composite-1 Surf, Anterior, Composite-3 Surf, Anterior, Fluoride, 2 Bitewings, missed appointment",
            "patientId": "02chirop-a123-b456-c789-d101112e1302",
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
        FlexSpine: {
            "first_name": "Flex",
            "last_name": "Spine",
            "email": "flex.spine@gmail.com",
            "mobile": "8326040145",
            "comment": "",
            "homephone": "",
            "appt_ehr_id": "332",
            "appointment_status": "complete",
            "appointment_status_ehr_key": "444",
            "confirmed_status_ehr_key": "444",
            "finalstatus": "complete",
            "unschedule_status": "",
            "confirmed_status": "not called",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "provider": [constantProviderBlock.defaultProvider],
            "appointmenttype": { "name": "New Patient Exam DR" },
            ...locationFields.austin,
            "engage": true,
            "pozative": true,
            "procedurecode": "T6452, T6462, T6472",
            "proceduredesc": "Post & Core, Root Canal, Root Canal",
            "patientId": "06chirop-a123-b456-c789-d101112e1306",
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        },
        BoneCare: {
            "first_name": "Bone",
            "last_name": "Care",
            "email": "bone.care@gmail.com",
            "mobile": "1122334455",
            "comment": "",
            "homephone": "",
            "appt_ehr_id": "336",
            "appointment_status": "missed",
            "appointment_status_ehr_key": "222",
            "confirmed_status_ehr_key": "222",
            "finalstatus": "missed",
            "unschedule_status": "",
            "confirmed_status": "appointment confirmed",
            "is_ehr_completed": true,
            "operatory_starttime": 0,
            "operatory_endtime": 0,
            "provider": [constantProviderBlock.defaultProvider],
            "appointmenttype": { "name": "New Patient Exam DR" },
            ...locationFields.austin,
            "engage": true,
            "pozative": true,
            "procedurecode": "T3522, T5833, T6245, T6255",
            "proceduredesc": "Composite-2 Surf, Anterior, Composite-2 Surf, Posterior, Bridge Pontic, PFM, Bridge Retainer, PFM",
            "patientId": "04chirop-a123-b456-c789-d101112e1304",
            "closure_preference": null,
            "closure_color": null,
            "groupId": null,
            "notes": ""
        }
    },
    closure: {
        Block_1: {
            "allow_book_appt": true,
            "appointment_status": "block",
            "appt_ehr_id": "",
            "birth_date": 0,
            "closure_color": "#072B40",
            "closure_preference": "{\"closureType\":\"once\"}",
            "confirmed_status": "",
            "engage": true,
            "end_time": 0,
            "first_name": "",
            "finalstatus": "block",
            "homephone": "",
            "is_confirm_recived": true,
            "is_ehr_completed": true,
            "last_name": "",
            "mobile": "",
            "notes": "",
            "operatory_endtime": 0,
            "operatory_starttime": 0,
            "procedurecode": "",
            "proceduredesc": "",
            "shedule_time": 0,
            "unschedule_status": "",
            "appointmenttype": { "name": "" },
            "pozative": true,
            ...locationFields.austin
        },
    },
}

const baseFields = { "status": true, "pozative": false, "engage": true, "error": null, "message": "Success", "offset": 330, "loctimezone": locationTimezone, }
const blockedApptsFields = {
    closure_1: {
        ...apptsBase.closure.Block_1,
        "comment": "Surgery or Emergency",
        "patient_ehr_id": "0",
        "_id": "block_id_1",
        "$id": "block_id_1",
        "groupId": "1",
        "sharedSlotId": 'closure_group_A',
    },
    closure_2: {
        ...apptsBase.closure.Block_1,
        "comment": "Scan Appointment",
        "patient_ehr_id": "0",
        "_id": "block_id_2",
        "$id": "block_id_2",
        "groupId": "2",
        "sharedSlotId": 'closure_group_B',
    },
}

export const appointmentlocationAppientmentPatientSchedulerMock = {
    dental: {
        ...baseFields,
        "data": [
            {
                ...apptsBase.dental.RuthCanal,
                "patient_ehr_id": "dental_patient_ehr_id_1",
                "_id": "01dental-a123-b456-c789-d101112e1301",
                "$id": "01dental-a123-b456-c789-d101112e1301",
                "sharedSlotId": 'first_level_group_A',
                "operatory": [constantOperatoryData.hygieneOp1],
                "provider": [constantProvidersDentalData.DENTON_CARE],
            },
            {
                ...apptsBase.dental.MileySmiley,
                "patient_ehr_id": "dental_patient_ehr_id_6",
                "_id": "06dental-a123-b456-c789-d101112e1306",
                "$id": "06dental-a123-b456-c789-d101112e1306",
                "sharedSlotId": 'first_level_group_C',
                "operatory": [constantOperatoryData.hygieneOp2],
                "provider": [constantProvidersDentalData.GRANT_GUMS],
            },
            {
                ...apptsBase.dental.PerryODontist,
                "patient_ehr_id": "dental_patient_ehr_id_4",
                "_id": "04dental-a123-b456-c789-d101112e1304",
                "$id": "04dental-a123-b456-c789-d101112e1304",
                "sharedSlotId": 'fourth_level_group_A',
                "operatory": [constantOperatoryData.operatory3],
                "provider": [constantProvidersDentalData.ORAL_LEE],
            },
            {
                ...apptsBase.dental.EveNamel,
                "patient_ehr_id": "dental_patient_ehr_id_2",
                "_id": "02dental-a123-b456-c789-d101112e1302",
                "$id": "02dental-a123-b456-c789-d101112e1302",
                "sharedSlotId": 'first_level_group_B',
                "operatory": [constantOperatoryData.operatory4],
                "provider": [constantProvidersDentalData.CAVITY_JONES],
            },
            { ...blockedApptsFields.closure_1, "operatory": [constantOperatoryData.operatory3], "provider": [constantProvidersDentalData.GRANT_GUMS], },
            { ...blockedApptsFields.closure_2, "operatory": [constantOperatoryData.operatory4], "provider": [constantProvidersDentalData.GRANT_GUMS], },
        ],
    },
    optometry: {
        ...baseFields,
        "data": [
            {
                ...apptsBase.optometry.CrystalClearview,
                "patient_ehr_id": "opto_patient_ehr_id_3",
                "_id": "038e6525-opto-b456-c789-d101112e1303",
                "$id": "038e6525-opto-b456-c789-d101112e1303",
                "sharedSlotId": 'first_level_group_A',
                "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
                "provider": [constantOperatoryOptoData.I_C_WRIGHT],
            },
            {
                ...apptsBase.optometry.EllieOVision,
                "patient_ehr_id": "opto_patient_ehr_id_4",
                "_id": "048e6525-opto-b456-c789-d101112e1304",
                "$id": "048e6525-opto-b456-c789-d101112e1304",
                "sharedSlotId": 'fourth_level_group_A',
                "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
                "provider": [constantOperatoryOptoData.AL_O_VEWELL],
            },
            {
                ...apptsBase.optometry.CeeVision,
                "patient_ehr_id": "opto_patient_ehr_id_2",
                "_id": "028e6525-opto-b456-c789-d101112e1302",
                "$id": "028e6525-opto-b456-c789-d101112e1302",
                "sharedSlotId": 'first_level_group_B',
                "operatory": [constantOperatoryOptoData.IMA_FOCUS],
                "provider": [constantOperatoryOptoData.IMA_FOCUS],
            },
            {
                ...apptsBase.optometry.ImaSeewell,
                "patient_ehr_id": "opto_patient_ehr_id_6",
                "_id": "068e6525-opto-b456-c789-d101112e1306",
                "$id": "068e6525-opto-b456-c789-d101112e1306",
                "sharedSlotId": 'first_level_group_C',
                "operatory": [constantOperatoryOptoData.RAY_T_LIGHTER],
                "provider": [constantOperatoryOptoData.RAY_T_LIGHTER],
            },
            { ...blockedApptsFields.closure_1, "operatory": [constantOperatoryOptoData.AL_O_VEWELL], "provider": [constantOperatoryOptoData.AL_O_VEWELL], },
            { ...blockedApptsFields.closure_2, "operatory": [constantOperatoryOptoData.IMA_FOCUS], "provider": [constantOperatoryOptoData.IMA_FOCUS], },
        ],
    },
    chiropractor: {
        ...baseFields,
        "data": [
            {
                ...apptsBase.chiropractor.AnitaCrack,
                "patient_ehr_id": "chiro_patient_ehr_id_2",
                "_id": "02chirop-a123-b456-c789-d101112e1302",
                "$id": "02chirop-a123-b456-c789-d101112e1302",
                "sharedSlotId": 'first_level_group_A',
                "operatory": [constantOperatoryData.hygieneOp1],
                "provider": [constantProvidersDentalData.DENTON_CARE],
            },
            {
                ...apptsBase.chiropractor.BoneCare,
                "patient_ehr_id": "chiro_patient_ehr_id_4",
                "_id": "04chirop-a123-b456-c789-d101112e1304",
                "$id": "04chirop-a123-b456-c789-d101112e1304",
                "sharedSlotId": 'fourth_level_group_A',
                "operatory": [constantOperatoryData.operatory3],
                "provider": [constantProvidersDentalData.GRANT_GUMS],
            },
            {
                ...apptsBase.chiropractor.AllyVertebrae,
                "patient_ehr_id": "chiro_patient_ehr_id_1",
                "_id": "01chirop-a123-b456-c789-d101112e1301",
                "$id": "01chirop-a123-b456-c789-d101112e1301",
                "sharedSlotId": 'first_level_group_B',
                "operatory": [constantOperatoryData.operatory4],
                "provider": [constantProvidersDentalData.ORAL_LEE],
            },
            {
                ...apptsBase.chiropractor.FlexSpine,
                "patient_ehr_id": "chiro_patient_ehr_id_6",
                "_id": "06chirop-a123-b456-c789-d101112e1306",
                "$id": "06chirop-a123-b456-c789-d101112e1306",
                "sharedSlotId": 'first_level_group_C',
                "operatory": [constantOperatoryData.hygieneOp2],
                "provider": [constantProvidersDentalData.CAVITY_JONES],
            },
            { ...blockedApptsFields.closure_1, "operatory": [constantOperatoryData.operatory3], "provider": [constantProvidersDentalData.GRANT_GUMS], },
            { ...blockedApptsFields.closure_2, "operatory": [constantOperatoryData.operatory4], "provider": [constantProvidersDentalData.GRANT_GUMS], },
        ]
    },
}