import { constantOperatoryData } from "../../constant-mock-data/constantOperatoryData.mock";
import { constantLocationData } from "../../constant-mock-data/constantLocationData.mock"
import { constantProviderBlock } from "../../constant-mock-data/constantOperatoryData.mock"

const locationTimezone = {
    "_id": constantLocationData.austin.id,
    "name": "Saskatchewan",
    "zone": "Canada/Saskatchewan",
    "gmt": "(GMT-06:00)",
    "alias": "saskatchewan",
    "is_active": true,
    "created_at": 1550131715928,
    "updated_at": 1550131715928,
    "deleted_at": null
}

const locationFields = Object.entries(constantLocationData).reduce(
    (acc, [key, loc]) => {
        acc[key] = {
            location: {
                application_name: "Eaglesoft",
                $id: loc.id,
                location: { $ref: "location", $id: loc.id },
            },
            appointmentlocationId: loc.id,
            appointmentlocationName: loc.name,
        };
        return acc;
    },
    {} as Record<keyof typeof constantLocationData,
        { location: { application_name: string; $id: string; location: { $ref: string; $id: string } }; appointmentlocationId: string; appointmentlocationName: string; }>
);

const apptsBase = {
    RollandOver_ID_1: {
        "first_name": "Rolland",
        "last_name": "Over",
        "email": "rolland.over@gmail.com",
        "mobile": "8326987944",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "329",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99213, 99212",
        "proceduredesc": "Established patient office visits, Established patient office visits",
        "patientId": "13chirop-a123-b456-c789-d101112e1313",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    AllyVertebrae_ID_2: {
        "first_name": "Ally",
        "last_name": "Vertebrae",
        "email": "ally.vertebrae@gmail.com",
        "mobile": "8326506958",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "331",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99215, 99214",
        "proceduredesc": "Established patient office visits, Established patient office visits",
        "patientId": "01chirop-a123-b456-c789-d101112e1301",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    AnitaCrack_ID_3: {
        "first_name": "Anita",
        "last_name": "Crack",
        "email": "anita.crack@gmail.com",
        "mobile": "8324897898",
        "comment": "",
        "homephone": "2027953213",
        "appt_ehr_id": "330",
        "appointment_status": "missed",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "missed",
        "engage": true,
        "pozative": true,
        // Assuming D9986 maps to a missed appointment code if one exists in the Chiro system, otherwise using a generic code
        "procedurecode": "99202, 99203, MISSED",
        "proceduredesc": "New patient office visits, New patient office visits, missed appointment",
        "patientId": "02chirop-a123-b456-c789-d101112e1302",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    FlexSpine_ID_5: {
        "first_name": "Flex",
        "last_name": "Spine",
        "email": "flex.spine@gmail.com",
        "mobile": "8326040145",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "332",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99204, 99205",
        "proceduredesc": "New Patient visits, New Patient visits",
        "patientId": "06chirop-a123-b456-c789-d101112e1306",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    AllyVertebrae_ID_6: {
        "first_name": "Ally",
        "last_name": "Vertebrae",
        "email": "ally.vertebrae@gmail.com",
        "mobile": "8326506958",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "333",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99214, 99213, 99212",
        "proceduredesc": "Established patient office visits, Established patient office visits, Established patient office visits",
        "patientId": "01chirop-a123-b456-c789-d101112e1301",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    AnitaCrack_ID_7: {
        "first_name": "Anita",
        "last_name": "Crack",
        "email": "anita.crack@gmail.com",
        "mobile": "9988776655",
        "comment": "",
        "homephone": "2027953213",
        "appt_ehr_id": "334",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "unconfirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99202, 99203, 99204",
        "proceduredesc": "New patient office visits, New patient office visits, New Patient visits",
        "patientId": "02chirop-a123-b456-c789-d101112e1302",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    BendEBack_ID_8: {
        "first_name": "Bend E.",
        "last_name": "Back",
        "email": "bend.e.back@gmail.com",
        "mobile": "7788990011",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "335",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "cancelled",
        "engage": true,
        "pozative": true,
        // Assuming D9987 maps to a cancelled appointment code if one exists in the Chiro system, otherwise using a generic code
        "procedurecode": "99205, 99204, CANCELLED",
        "proceduredesc": "New Patient visits, New Patient visits, cancelled appointment",
        "patientId": "03chirop-a123-b456-c789-d101112e1303",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    TimberlyNeck_ID_9: {
        "first_name": "Timberly",
        "last_name": "Neck",
        "email": "timberly.neck@gmail.com",
        "mobile": "2233445566",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "346",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99213, 99214, 99215",
        "proceduredesc": "Established patient office visits, Established patient office visits, Established patient office visits",
        "patientId": "14chirop-a123-b456-c789-d101112e1314",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    BoneCare_ID_10: {
        "first_name": "Bone",
        "last_name": "Care",
        "email": "bone.care@gmail.com",
        "mobile": "1122334455",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "336",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99202, 99203, 99204",
        "proceduredesc": "New patient office visits, New patient office visits, New Patient visits",
        "patientId": "04chirop-a123-b456-c789-d101112e1304",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    ChiroSpondylus_ID_11: {
        "first_name": "Chiro",
        "last_name": "Spondylus",
        "email": "chiro.spondylus@gmail.com",
        "mobile": "2233445566",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "337",
        "appointment_status": "unconfirmed",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "unconfirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99211, 99212, 99213",
        "proceduredesc": "Established patient office visits, Established patient office visits, Established patient office visits",
        "patientId": "05chirop-a123-b456-c789-d101112e1305",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    FlexSpine_ID_12: {
        "first_name": "Flex",
        "last_name": "Spine",
        "email": "flex.spine@gmail.com",
        "mobile": "3344556677",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "338",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99214, 99215",
        "proceduredesc": "Established patient office visits, Established patient office visits",
        "patientId": "06chirop-a123-b456-c789-d101112e1306",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    JustinAlignment_ID_13: {
        "first_name": "Justin",
        "last_name": "Alignment",
        "email": "justin.alignment@gmail.com",
        "mobile": "4455667788",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "339",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "missed",
        "engage": true,
        "pozative": true,
        // Assuming D9986 maps to a missed appointment code if one exists in the Chiro system, otherwise using a generic code
        "procedurecode": "99205, 99204, MISSED",
        "proceduredesc": "New Patient visits, New Patient visits, missed appointment",
        "patientId": "07chirop-a123-b456-c789-d101112e1307",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    KneedaFix_ID_14: {
        "first_name": "Kneeda",
        "last_name": "Fix",
        "email": "kneeda.fix@gmail.com",
        "mobile": "5566778899",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "340",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99211, 99212, 99213",
        "proceduredesc": "Established patient office visits, Established patient office visits, Established patient office visits",
        "patientId": "08chirop-a123-b456-c789-d101112e1308",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    LaceyBone_ID_15: {
        "first_name": "Lacey",
        "last_name": "Bone",
        "email": "lacey.bone@gmail.com",
        "mobile": "6677889900",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "341",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "unconfirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99202, 99203, 99204, 99205",
        "proceduredesc": "New patient office visits, New patient office visits, New Patient visits, New Patient visits",
        "patientId": "09chirop-a123-b456-c789-d101112e1309",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    LeslieBackus_ID_16: {
        "first_name": "Leslie",
        "last_name": "Backus",
        "email": "leslie.backus@gmail.com",
        "mobile": "7788990011",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "342",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99211, 99212, 99213, 99214",
        "proceduredesc": "Established patient office visits, Established patient office visits, Established patient office visits, Established patient office visits",
        "patientId": "10chirop-a123-b456-c789-d101112e1310",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    PaigeTurner_ID_17: {
        "first_name": "Paige",
        "last_name": "Turner",
        "email": "paige.turner@gmail.com",
        "mobile": "8899001122",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "343",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "missed",
        "engage": true,
        "pozative": true,
        // Assuming D9986 maps to a missed appointment code if one exists in the Chiro system, otherwise using a generic code
        "procedurecode": "99205, 99204, MISSED",
        "proceduredesc": "New Patient visits, New Patient visits, missed appointment",
        "patientId": "11chirop-a123-b456-c789-d101112e1311",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    RheaAdjust_ID_18: {
        "first_name": "Rhea",
        "last_name": "Adjust",
        "email": "rhea.adjust@gmail.com",
        "mobile": "9900112233",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "344",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99215, 99214, 99213",
        "proceduredesc": "Established patient office visits, Established patient office visits, Established patient office visits",
        "patientId": "12chirop-a123-b456-c789-d101112e1312",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    RollandOver_ID_19: {
        "first_name": "Rolland",
        "last_name": "Over",
        "email": "rolland.over@gmail.com",
        "mobile": "1122334455",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "345",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        // Assuming D9987 maps to a cancelled appointment code if one exists in the Chiro system, otherwise using a generic code
        "procedurecode": "99211, 99212, CANCELLED",
        "proceduredesc": "Established patient office visits, Established patient office visits, cancelled appointment",
        "patientId": "13chirop-a123-b456-c789-d101112e1313",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    ToriSpinal_ID_20: {
        "first_name": "Tori",
        "last_name": "Spinal",
        "email": "tori.spinal@gmail.com",
        "mobile": "3344556677",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "347",
        "appointment_status": "unconfirmed",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [constantProviderBlock.defaultProvider],
        "appointmenttype": { "name": "New Patient Exam DR" },
        ...locationFields.austin,
        "finalstatus": "unconfirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99203, 99202, 99201", // Added 99201 for variety although not in your list
        "proceduredesc": "New patient office visits, New patient office visits, New patient office visits",
        "patientId": "15chirop-a123-b456-c789-d101112e1315",
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    Block_ID_4: {
        "last_name": "",
        "email": "",
        "mobile": "",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "",
        "appointment_status": "block",
        "unschedule_status": "",
        "confirmed_status": "block",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [],
        "appointmenttype": { "name": "Lunch" },
        ...locationFields.austin,
        "finalstatus": "block",
        "engage": true,
        "pozative": true,
        "procedurecode": "",
        "proceduredesc": "",
        "patientId": "",
        "closure_preference": "{\"closureType\":\"once\"}",
        "closure_color": "#072B40",
        "groupId": "",
        "notes": ""
    }
}

export const appointmentlocation_appientment_patient_true_chiro_mock = {
    "status": true, "pozative": false, "engage": true, "error": null, "message": "Success", "offset": 330,
    "loctimezone": locationTimezone,
    "data": [
        {
            ...apptsBase.AllyVertebrae_ID_2,
            patient_ehr_id: "chiro-patient-ehr-id-1", _id: "id-2", $id: "id-2",
            sharedSlotId: 'morningGroupA',
            operatory: [constantOperatoryData.operatory4],
        },
        {
            ...apptsBase.KneedaFix_ID_14,
            patient_ehr_id: "chiro-patient-ehr-id-2", _id: "id-3", $id: "id-3",
            sharedSlotId: 'morningGroupB',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.RheaAdjust_ID_18,
            patient_ehr_id: "chiro-patient-ehr-id-3", _id: "id-4", $id: "id-4",
            sharedSlotId: 'morningGroupC',
            operatory: [constantOperatoryData.operatory4],
        },
        {
            ...apptsBase.LeslieBackus_ID_16,
            patient_ehr_id: "chiro-patient-ehr-id-4", _id: "id-5", $id: "id-5",
            sharedSlotId: 'afternoonGroupA',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.RollandOver_ID_1,
            patient_ehr_id: "chiro-patient-ehr-id-5", _id: "id-6", $id: "id-6",
            sharedSlotId: 'afternoonGroupB',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.JustinAlignment_ID_13,
            patient_ehr_id: "chiro-patient-ehr-id-6", _id: "id-7", $id: "id-7",
            sharedSlotId: 'afternoonGroupC',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.LaceyBone_ID_15,
            patient_ehr_id: "chiro-patient-ehr-id-7", _id: "id-8", $id: "id-8",
            sharedSlotId: 'morningGroupA',
            operatory: [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptsBase.FlexSpine_ID_5,
            patient_ehr_id: "chiro-patient-ehr-id-8", _id: "id-9", $id: "id-9",
            sharedSlotId: 'morningGroupB',
            operatory: [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptsBase.ChiroSpondylus_ID_11,
            patient_ehr_id: "chiro-patient-ehr-id-9", _id: "id-10", $id: "id-10",
            sharedSlotId: 'morningGroupC',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.ChiroSpondylus_ID_11,
            "patient_ehr_i": "chiro-patient-ehr-id-10", _id: "id-11", $id: "id-11",
            sharedSlotId: 'afternoonGroupA',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.AnitaCrack_ID_3,
            "patient_ehr_i": "chiro-patient-ehr-id-11", _id: "id-12", $id: "id-12",
            sharedSlotId: 'afternoonGroupB',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.BoneCare_ID_10,
            "patient_ehr_i": "chiro-patient-ehr-id-12", _id: "id-13", $id: "id-13",
            sharedSlotId: 'afternoonGroupC',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.TimberlyNeck_ID_9,
            "patient_ehr_i": "chiro-patient-ehr-id-13", _id: "id-14", $id: "id-14",
            sharedSlotId: 'morningGroupA',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.ToriSpinal_ID_20,
            "patient_ehr_i": "chiro-patient-ehr-id-14", _id: "id-15", $id: "id-15",
            sharedSlotId: 'morningGroupC',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.BendEBack_ID_8,
            "patient_ehr_i": "chiro-patient-ehr-id-15", _id: "id-16", $id: "id-16",
            sharedSlotId: 'morningGroupC',
            operatory: [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptsBase.JustinAlignment_ID_13,
            "patient_ehr_i": "chiro-patient-ehr-id-16", _id: "id-17", $id: "id-17",
            sharedSlotId: 'afternoonGroupA',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.PaigeTurner_ID_17,
            "patient_ehr_i": "chiro-patient-ehr-id-17", _id: "id-18", $id: "id-18",
            sharedSlotId: 'afternoonGroupB',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.AllyVertebrae_ID_6,
            "patient_ehr_i": "chiro-patient-ehr-id-18", _id: "id-19", $id: "id-19",
            sharedSlotId: 'afternoonGroupC',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.RheaAdjust_ID_18,
            "patient_ehr_i": "chiro-patient-ehr-id-19", _id: "id-20", $id: "id-20",
            sharedSlotId: 'morningGroupA',
            operatory: [constantOperatoryData.operatory4],
        },
        {
            ...apptsBase.TimberlyNeck_ID_9,
            "patient_ehr_i": "chiro-patient-ehr-id-20", _id: "id-21", $id: "id-21",
            sharedSlotId: 'morningGroupB',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.AnitaCrack_ID_7,
            "patient_ehr_i": "chiro-patient-ehr-id-21", _id: "id-22", $id: "id-22",
            sharedSlotId: 'morningGroupC',
            operatory: [constantOperatoryData.operatory4],
        },
        {
            ...apptsBase.JustinAlignment_ID_13,
            "patient_ehr_i": "chiro-patient-ehr-id-22", _id: "id-23", $id: "id-23",
            sharedSlotId: 'afternoonGroupA',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.JustinAlignment_ID_13,
            "patient_ehr_i": "chiro-patient-ehr-id-23", _id: "id-24", $id: "id-24",
            sharedSlotId: 'afternoonGroupB',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.LaceyBone_ID_15,
            "patient_ehr_i": "chiro-patient-ehr-id-24", _id: "id-25", $id: "id-25",
            sharedSlotId: 'afternoonGroupC',
            operatory: [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptsBase.PaigeTurner_ID_17,
            "patient_ehr_i": "chiro-patient-ehr-id-25", _id: "id-26", $id: "id-26",
            sharedSlotId: 'morningGroupA',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.ToriSpinal_ID_20,
            "patient_ehr_i": "chiro-patient-ehr-id-26", _id: "id-27", $id: "id-27",
            sharedSlotId: 'morningGroupC',
            operatory: [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptsBase.RollandOver_ID_19,
            "patient_ehr_i": "chiro-patient-ehr-id-27", _id: "id-28", $id: "id-28",
            sharedSlotId: 'morningGroupC',
            operatory: [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptsBase.BoneCare_ID_10,
            "patient_ehr_i": "chiro-patient-ehr-id-28", _id: "id-29", $id: "id-29",
            sharedSlotId: 'afternoonGroupA',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.KneedaFix_ID_14,
            "patient_ehr_i": "chiro-patient-ehr-id-29", _id: "id-30", $id: "id-30",
            sharedSlotId: 'afternoonGroupB',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.BendEBack_ID_8,
            "patient_ehr_i": "chiro-patient-ehr-id-30", _id: "id-31", $id: "id-31",
            sharedSlotId: 'afternoonGroupC',
            operatory: [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptsBase.LeslieBackus_ID_16,
            "patient_ehr_i": "chiro-patient-ehr-id-31", _id: "id-32", $id: "id-32",
            sharedSlotId: 'morningGroupA',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.FlexSpine_ID_12,
            "patient_ehr_i": "chiro-patient-ehr-id-32", _id: "id-33", $id: "id-33",
            sharedSlotId: 'morningGroupB',
            operatory: [constantOperatoryData.operatory4],
        },
        {
            ...apptsBase.Block_ID_4,
            "first_name": "Surgery or Emergency", "patient_ehr_id": "0", _id: "id-1", $id: "id-1",
            sharedSlotId: 'Blockout1',
            operatory: [constantOperatoryData.operatory3],
        },
        {
            ...apptsBase.Block_ID_4,
            "first_name": "Scan Appointment", "patient_ehr_id": "0", _id: "id-34", $id: "id-34",
            sharedSlotId: 'Blockout2',
            operatory: [constantOperatoryData.operatory4]
        },
    ],
};