import { constantOperatoryData } from "../../constant-mock-data/constantOperatoryData.mock";
import { constantLocationData } from "../../constant-mock-data/constantLocationData.mock"
import { constantProviderBlock } from "../../constant-mock-data/constantOperatoryData.mock"

const locationTimezone = {
    "_id": constantLocationData.austin.id,
    "name": "Saskatchewan",
    "zone": "Canada/Saskatchewan",
    "gmt": "(GMT-06:00)",
    "alias": "saskatchewan",
    "is_active": true,
    "created_at": 1550131715928,
    "updated_at": 1550131715928,
    "deleted_at": null
}

const locationObj = {
    "application_name": "Eaglesoft",
    "$id": constantLocationData.austin.id,
    "location": {
        "$ref": "location",
        "$id": constantLocationData.austin.id
    }
}

export const apptJoeAdam_ID_1 = {
    "first_name": "Joe",
    "last_name": "Adam",
    "email": "joe.adam@gmail.com",
    "mobile": "8326987944",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "329",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "appointment confirmed",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "confirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T4528, T4538, T4548",
    "proceduredesc": "Amalgam-1 Surf, Amalgam-2 Surf, Amalgam-3 Surf",
    "patientId": "13dental-a123-b456-c789-d101112e1313",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptRuthCanal_ID_2 = {
    "first_name": "Ruth",
    "last_name": "Canal",
    "email": "ruth.canal@gmail.com",
    "mobile": "8326506958",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "331",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "appointment confirmed",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "completed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T5823, T9836",
    "proceduredesc": "Bridge Pontic, Mandibular Denture",
    "patientId": "01dental-a123-b456-c789-d101112e1301",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptEveNamel_ID_3 = {
    "first_name": "Eve",
    "last_name": "Namel",
    "email": "eve.namel@gmail.com",
    "mobile": "8324897898",
    "comment": "",
    "homephone": "2027953213",
    "appt_ehr_id": "330",
    "appointment_status": "missed",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "missed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T3512, T3532, T1254, T1632, D9986",
    "proceduredesc": "Composite-1 Surf, Anterior, Composite-3 Surf, Anterior, Fluoride, 2 Bitewings, missed appointment",
    "patientId": "02dental-a123-b456-c789-d101112e1302",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptMileySmiley_ID_5 = {
    "first_name": "Miley",
    "last_name": "Smiley",
    "email": "miley.smiley@gmail.com",
    "mobile": "8326040145",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "332",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "confirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T6452, T6462, T6472",
    "proceduredesc": "Post & Core, Root Canal, Root Canal",
    "patientId": "06dental-a123-b456-c789-d101112e1306",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptRuthCanal_ID_6 = {
    "first_name": "Ruth",
    "last_name": "Canal",
    "email": "ruth.canal@gmail.com",
    "mobile": "8326506958",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "333",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "confirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T3542, D0274, D2392, N1254",
    "proceduredesc": "Composite-4 Surf, Anterior or More Surfaces, D0274, D2392, Watch",
    "patientId": "01dental-a123-b456-c789-d101112e1301",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptEveNamel_ID_7 = {
    "first_name": "Eve",
    "last_name": "Namel",
    "email": "eve.namel@gmail.com",
    "mobile": "9988776655",
    "comment": "",
    "homephone": "2027953213",
    "appt_ehr_id": "334",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "appointment confirmed",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "unconfirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T7966, T5843, D4342, T1546",
    "proceduredesc": "Root Canal, Bicuspid, Composite-3 Surf, Posterior, D4342, Intraoral Periapical Film",
    "patientId": "02dental-a123-b456-c789-d101112e1302",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptDanTure_ID_8 = {
    "first_name": "DAN",
    "last_name": "TURE",
    "email": "dan.ture@gmail.com",
    "mobile": "7788990011",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "335",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "cancelled",
    "engage": true,
    "pozative": true,
    "procedurecode": "T9826, D0120, T6357, D9987",
    "proceduredesc": "Maxillary Denture, Resto., Extraction, cancelled appointment",
    "patientId": "03dental-a123-b456-c789-d101112e1303",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptMandiBill_ID_9 = {
    "first_name": "Mandi",
    "last_name": "BILL",
    "email": "mandi.bill@gmail.com",
    "mobile": "2233445566",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "346",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "appointment confirmed",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "confirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T7956, D0230, D9630, T1698, D4341",
    "proceduredesc": "Root Canal, Anterior, D0230, D9630, 4 Bitewings, D4341",
    "patientId": "14dental-a123-b456-c789-d101112e1314",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptPerryOdontist_ID_10 = {
    "first_name": "PERRY",
    "last_name": "O'DONTIST",
    "email": "perry.odontist@gmail.com",
    "mobile": "1122334455",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "336",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "appointment confirmed",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "confirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T3522, T5833, T6245, T6255",
    "proceduredesc": "Composite-2 Surf, Anterior, Composite-2 Surf, Posterior, Bridge Pontic, PFM, Bridge Retainer, PFM",
    "patientId": "04dental-a123-b456-c789-d101112e1304",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptPearlWhite_ID_11 = {
    "first_name": "PEARL",
    "last_name": "WHITE",
    "email": "pearl.white@gmail.com",
    "mobile": "2233445566",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "337",
    "appointment_status": "unconfirmed",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "unconfirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T6531, T2345, T1356, T1665",
    "proceduredesc": "PFM Crown, Build Up, Exam, Panoramic",
    "patientId": "05dental-a123-b456-c789-d101112e1305",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptMileySmiley_ID_12 = {
    "first_name": "MILEY",
    "last_name": "SMILEY",
    "email": "miley.smiley@gmail.com",
    "mobile": "3344556677",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "338",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "appointment confirmed",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "completed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T4558, T3541, D4341, D1120",
    "proceduredesc": "Amalgam-4 Surf or More Surfaces, Prophy, Adult, D4341, D1120",
    "patientId": "06dental-a123-b456-c789-d101112e1306",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptInaCisor_ID_13 = {
    "first_name": "INA",
    "last_name": "CISOR",
    "email": "ina.cisor@gmail.com",
    "mobile": "4455667788",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "339",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "missed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T5853, T7976, D1110, D9986",
    "proceduredesc": "Composite-4 Surf, Posterior or More Surfaces, Root Canal, Molar, D1110, missed appointment",
    "patientId": "07dental-a123-b456-c789-d101112e1307",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptAnnieSteshia_ID_14 = {
    "first_name": "ANNIE",
    "last_name": "STESHIA",
    "email": "annie.steshia@gmail.com",
    "mobile": "5566778899",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "340",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "appointment confirmed",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "confirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "D0220, D2393, D1351, D4127, D4101",
    "proceduredesc": "D0220, restoirative, D1351, Uncate, unctae",
    "patientId": "08dental-a123-b456-c789-d101112e1308",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptSarahBellum_ID_15 = {
    "first_name": "SARAH",
    "last_name": "BELLUM",
    "email": "sarah.bellum@gmail.com",
    "mobile": "6677889900",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "341",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "unconfirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T3512, D0274, T1632, D1110, D1120, D4910",
    "proceduredesc": "Composite-1 Surf, Anterior, D0274, 2 Bitewings, D1110, D1120, D4910",
    "patientId": "09dental-a123-b456-c789-d101112e1309",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptErnestFlossy_ID_16 = {
    "first_name": "ERNEST",
    "last_name": "FLOSSY",
    "email": "ernest.flossy@gmail.com",
    "mobile": "7788990011",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "342",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "appointment confirmed",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "completed",
    "engage": true,
    "pozative": true,
    "procedurecode": "D2650, D2651, D4342, T1698, T1254",
    "proceduredesc": "Restorative, Restorative, D4342, 4 Bitewings, Fluoride",
    "patientId": "10dental-a123-b456-c789-d101112e1310",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptPhilLing_ID_17 = {
    "first_name": "PHIL",
    "last_name": "LING",
    "email": "phil.ling@gmail.com",
    "mobile": "8899001122",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "343",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "missed",
    "engage": true,
    "pozative": true,
    "procedurecode": "D0140, D1206, D4355, T6357, D9986",
    "proceduredesc": "limited oral evaluation - problem focused, D1206, D4355, Extraction, missed appointment",
    "patientId": "11dental-a123-b456-c789-d101112e1311",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptMoeLars_ID_18 = {
    "first_name": "MOE",
    "last_name": "LARS",
    "email": "moe.lars@gmail.com",
    "mobile": "9900112233",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "344",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "appointment confirmed",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "completed",
    "engage": true,
    "pozative": true,
    "procedurecode": "D0140, D1206, T1546, T1665",
    "proceduredesc": "limited oral evaluation - problem focused, D1206, Intraoral Periapical Film, Panoramic",
    "patientId": "12dental-a123-b456-c789-d101112e1312",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptJoeAdam_ID_19 = {
    "first_name": "JOE",
    "last_name": "ADAM",
    "email": "joe.adam@gmail.com",
    "mobile": "1122334455",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "345",
    "appointment_status": "schedule",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "completed",
    "engage": true,
    "pozative": true,
    "procedurecode": "T6482, N1255, T1254, D9987",
    "proceduredesc": "Root Canal, Retreat Molar, Watch Surface, Fluoride, cancelled appointment",
    "patientId": "13dental-a123-b456-c789-d101112e1313",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}

export const apptGingerVitis_ID_20 = {
    "first_name": "GINGER",
    "last_name": "VITIS",
    "email": "ginger.vitis@gmail.com",
    "mobile": "3344556677",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "347",
    "appointment_status": "unconfirmed",
    "unschedule_status": "",
    "confirmed_status": "not called",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [constantProviderBlock.defaultProvider],
    "appointmenttype": { "name": "New Patient Exam DR" },
    "location": locationObj,
    "finalstatus": "unconfirmed",
    "engage": true,
    "pozative": true,
    "procedurecode": "D0220, D2393, D4341, D1120, D4910",
    "proceduredesc": "D0220, restoirative, D4341, D1120, D4910",
    "patientId": "15dental-a123-b456-c789-d101112e1315",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": null,
    "closure_color": null,
    "groupId": null,
    "notes": ""
}


export const apptBlock_ID_4 = {
    "last_name": "",
    "email": "",
    "mobile": "",
    "comment": "",
    "homephone": "",
    "appt_ehr_id": "",
    "appointment_status": "block",
    "unschedule_status": "",
    "confirmed_status": "block",
    "is_ehr_completed": true,
    "operatory_starttime": 0,
    "operatory_endtime": 0,
    "provider": [],
    "appointmenttype": { "name": "Lunch" },
    "location": locationObj,
    "finalstatus": "block",
    "engage": true,
    "pozative": true,
    "procedurecode": "",
    "proceduredesc": "",
    "patientId": "",
    "appointmentlocationId": constantLocationData.austin.id,
    "appointmentlocationName": constantLocationData.austin.name,
    "closure_preference": "{\"closureType\":\"once\"}",
    "closure_color": "#072B40",
    "groupId": "",
    "notes": ""
}

export const appointmentlocation_appientment_patient_true_mock = {
    "status": true,
    "pozative": false,
    "engage": true,
    "data": [
        {
            ...apptRuthCanal_ID_2,
            "patient_ehr_id": "mock-patient-ehr-id-1",
            "_id": "id-2",
            "$id": "id-2",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryData.operatory4],
        },
        {
            ...apptAnnieSteshia_ID_14,
            "patient_ehr_id": "mock-patient-ehr-id-2",
            "_id": "id-3",
            "$id": "id-3",
            "sharedSlotId": 'morningGroupB',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptMoeLars_ID_18,
            "patient_ehr_id": "mock-patient-ehr-id-3",
            "_id": "id-4",
            "$id": "id-4",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryData.operatory4],
        },
        {
            ...apptErnestFlossy_ID_16,
            "patient_ehr_id": "mock-patient-ehr-id-4",
            "_id": "id-5",
            "$id": "id-5",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptJoeAdam_ID_1,
            "patient_ehr_id": "mock-patient-ehr-id-5",
            "_id": "id-6",
            "$id": "id-6",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptInaCisor_ID_13,
            "patient_ehr_id": "mock-patient-ehr-id-6",
            "_id": "id-7",
            "$id": "id-7",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptSarahBellum_ID_15,
            "patient_ehr_id": "mock-patient-ehr-id-7",
            "_id": "id-8",
            "$id": "id-8",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptMileySmiley_ID_5,
            "patient_ehr_id": "mock-patient-ehr-id-8",
            "_id": "id-9",
            "$id": "id-9",
            "sharedSlotId": 'morningGroupB',
            "operatory": [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptPearlWhite_ID_11,
            "patient_ehr_id": "mock-patient-ehr-id-9",
            "_id": "id-10",
            "$id": "id-10",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptPearlWhite_ID_11,
            "patient_ehr_id": "mock-patient-ehr-id-10",
            "_id": "id-11",
            "$id": "id-11",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptEveNamel_ID_3,
            "patient_ehr_id": "mock-patient-ehr-id-11",
            "_id": "id-12",
            "$id": "id-12",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptPerryOdontist_ID_10,
            "patient_ehr_id": "mock-patient-ehr-id-12",
            "_id": "id-13",
            "$id": "id-13",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptMandiBill_ID_9,
            "patient_ehr_id": "mock-patient-ehr-id-13",
            "_id": "id-14",
            "$id": "id-14",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptGingerVitis_ID_20,
            "patient_ehr_id": "mock-patient-ehr-id-14",
            "_id": "id-15",
            "$id": "id-15",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptDanTure_ID_8,
            "patient_ehr_id": "mock-patient-ehr-id-15",
            "_id": "id-16",
            "$id": "id-16",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptInaCisor_ID_13,
            "patient_ehr_id": "mock-patient-ehr-id-16",
            "_id": "id-17",
            "$id": "id-17",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptPhilLing_ID_17,
            "patient_ehr_id": "mock-patient-ehr-id-17",
            "_id": "id-18",
            "$id": "id-18",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptRuthCanal_ID_6,
            "patient_ehr_id": "mock-patient-ehr-id-18",
            "_id": "id-19",
            "$id": "id-19",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptMoeLars_ID_18,
            "patient_ehr_id": "mock-patient-ehr-id-19",
            "_id": "id-20",
            "$id": "id-20",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryData.operatory4],
        },
        {
            ...apptMandiBill_ID_9,
            "patient_ehr_id": "mock-patient-ehr-id-20",
            "_id": "id-21",
            "$id": "id-21",
            "sharedSlotId": 'morningGroupB',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptEveNamel_ID_7,
            "patient_ehr_id": "mock-patient-ehr-id-21",
            "_id": "id-22",
            "$id": "id-22",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryData.operatory4],
        },
        {
            ...apptInaCisor_ID_13,
            "patient_ehr_id": "mock-patient-ehr-id-22",
            "_id": "id-23",
            "$id": "id-23",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptInaCisor_ID_13,
            "patient_ehr_id": "mock-patient-ehr-id-23",
            "_id": "id-24",
            "$id": "id-24",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptSarahBellum_ID_15,
            "patient_ehr_id": "mock-patient-ehr-id-24",
            "_id": "id-25",
            "$id": "id-25",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptPhilLing_ID_17,
            "patient_ehr_id": "mock-patient-ehr-id-25",
            "_id": "id-26",
            "$id": "id-26",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptGingerVitis_ID_20,
            "patient_ehr_id": "mock-patient-ehr-id-26",
            "_id": "id-27",
            "$id": "id-27",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryData.hygieneOp1],
        },
        {
            ...apptJoeAdam_ID_19,
            "patient_ehr_id": "mock-patient-ehr-id-27",
            "_id": "id-28",
            "$id": "id-28",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptPerryOdontist_ID_10,
            "patient_ehr_id": "mock-patient-ehr-id-28",
            "_id": "id-29",
            "$id": "id-29",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptAnnieSteshia_ID_14,
            "patient_ehr_id": "mock-patient-ehr-id-29",
            "_id": "id-30",
            "$id": "id-30",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptDanTure_ID_8,
            "patient_ehr_id": "mock-patient-ehr-id-30",
            "_id": "id-31",
            "$id": "id-31",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryData.hygieneOp2],
        },
        {
            ...apptErnestFlossy_ID_16,
            "patient_ehr_id": "mock-patient-ehr-id-31",
            "_id": "id-32",
            "$id": "id-32",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptMileySmiley_ID_12,
            "patient_ehr_id": "mock-patient-ehr-id-32",
            "_id": "id-33",
            "$id": "id-33",
            "sharedSlotId": 'morningGroupB',
            "operatory": [constantOperatoryData.operatory4],
        },
        {
            ...apptBlock_ID_4,
            "first_name": "Surgery or Emergency",
            "patient_ehr_id": "0",
            "_id": "id-1",
            "$id": "id-1",
            "sharedSlotId": 'Blockout1',
            "operatory": [constantOperatoryData.operatory3],
        },
        {
            ...apptBlock_ID_4,
            "first_name": "Scan Appointment",
            "patient_ehr_id": "0",
            "_id": "id-34",
            "$id": "id-34",
            "sharedSlotId": 'Blockout2',
            "operatory": [constantOperatoryData.operatory4]
        },
        // {
        //     ...apptBlock_ID_4,
        //     "first_name": "Breakfast",
        //     "patient_ehr_id": "0",
        //     "_id": "id-35",
        //     "$id": "id-35",
        //     "sharedSlotId": 'Blockout3',
        //     "operatory": [constantOperatoryData.hygieneOp1]
        // },
        // {
        //     ...apptBlock_ID_4,
        //     "first_name": "Dinner",
        //     "patient_ehr_id": "0",
        //     "_id": "id-36",
        //     "$id": "id-36",
        //     "sharedSlotId": 'Blockout4',
        //     "operatory": [constantOperatoryData.hygieneOp1]
        // },
        // {
        //     ...apptBlock_ID_4,
        //     "first_name": "Dinner",
        //     "patient_ehr_id": "0",
        //     "_id": "id-37",
        //     "$id": "id-37",
        //     "sharedSlotId": 'Blockout4',
        //     "operatory": [constantOperatoryData.operatory4]
        // },

    ],
    "loctimezone": locationTimezone,
    "error": null,
    "message": "Success",
    "offset": 330
};