import { constantOperatoryOptoData } from "../../constant-mock-data/constantOperatoryData.mock";
import { constantLocationData } from "../../constant-mock-data/constantLocationData.mock"

const locationTimezone = {
    "_id": constantLocationData.austin.id,
    "name": "Saskatchewan",
    "zone": "Canada/Saskatchewan",
    "gmt": "(GMT-06:00)",
    "alias": "saskatchewan",
    "is_active": true,
    "created_at": 1550131715928,
    "updated_at": 1550131715928,
    "deleted_at": null
}

const locationObj = {
    "application_name": "Eaglesoft",
    "$id": constantLocationData.austin.id,
    "location": { "$ref": "location", "$id": constantLocationData.austin.id }
}

const apptsBase = {
    Peyton_L_Specter_ID_1: {
        "first_name": "Peyton L.",
        "last_name": "Specter",
        "email": "peyton.l.specter@gmail.com",
        "mobile": "8326987944",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "329",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "92004",
        "proceduredesc": "Comprehensive Eye Exam - new patient",
        "patientId": "138e6525-opto-b456-c789-d101112e1313",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    BrittneyVision_ID_2: {
        "first_name": "Brittney",
        "last_name": "Vision",
        "email": "brittney.vision@gmail.com",
        "mobile": "8326506958",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "331",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        "procedurecode": "S0620",
        "proceduredesc": "Vision Examination - new patient",
        "patientId": "018e6525-opto-b456-c789-d101112e1301",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    CeeVision_ID_3: {
        "first_name": "Cee",
        "last_name": "Vision",
        "email": "cee.vision@gmail.com",
        "mobile": "8324897898",
        "comment": "",
        "homephone": "2027953213",
        "appt_ehr_id": "330",
        "appointment_status": "missed",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "missed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99204, 92004",
        "proceduredesc": "E&M Level 4 - new patient - comprehensive exam, Comprehensive Eye Exam - new patient",
        "patientId": "028e6525-opto-b456-c789-d101112e1302",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    ImaSeewell_ID_5: {
        "first_name": "Ima",
        "last_name": "Seewell",
        "email": "ima.seewell@gmail.com",
        "mobile": "8326040145",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "332",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99203",
        "proceduredesc": "E&M Level 3 - new patient - detailed exam",
        "patientId": "068e6525-opto-b456-c789-d101112e1306",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    BrittneyVision_ID_6: {
        "first_name": "Brittney",
        "last_name": "Vision",
        "email": "brittney.vision@gmail.com",
        "mobile": "8326506958",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "333",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "92004, 99204",
        "proceduredesc": "Comprehensive Eye Exam - new patient, E&M Level 4 - new patient - comprehensive exam",
        "patientId": "018e6525-opto-b456-c789-d101112e1301",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    CeeVision_ID_7: {
        "first_name": "Cee",
        "last_name": "Vision",
        "email": "cee.vision@gmail.com",
        "mobile": "9988776655",
        "comment": "",
        "homephone": "2027953213",
        "appt_ehr_id": "334",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "unconfirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "92004",
        "proceduredesc": "Comprehensive Eye Exam - new patient",
        "patientId": "028e6525-opto-b456-c789-d101112e1302",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    CrystalClearview_ID_8: {
        "first_name": "Crystal",
        "last_name": "Clearview",
        "email": "crystal.clearview@gmail.com",
        "mobile": "7788990011",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "335",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "cancelled",
        "engage": true,
        "pozative": true,
        "procedurecode": "92002",
        "proceduredesc": "Ophthalmological Exam - Intermediate - new patient",
        "patientId": "038e6525-opto-b456-c789-d101112e1303",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    Ray_N_Shine_ID_9: {
        "first_name": "Ray N.",
        "last_name": "Shine",
        "email": "ray.n..bill@gmail.com",
        "mobile": "2233445566",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "346",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "S0620",
        "proceduredesc": "Vision Examination - new patient",
        "patientId": "148e6525-opto-b456-c789-d101112e1314",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    EllieOVision_ID_10: {
        "first_name": "Ellie O.",
        "last_name": "Vision",
        "email": "ellie.o.vision@gmail.com",
        "mobile": "1122334455",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "336",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "92004",
        "proceduredesc": "Comprehensive Eye Exam - new patient",
        "patientId": "048e6525-opto-b456-c789-d101112e1304",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    GailLFogg_ID_11: {
        "first_name": "Gail L.",
        "last_name": "Fogg",
        "email": "gail.l.fogg@gmail.com",
        "mobile": "2233445566",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "337",
        "appointment_status": "unconfirmed",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "unconfirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99205",
        "proceduredesc": "E&M Level 5 - new patient - comprehensive exam",
        "patientId": "058e6525-opto-b456-c789-d101112e1305",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    ImaSeewell_ID_12: {
        "first_name": "Ima",
        "last_name": "Seewell",
        "email": "ima.seewell@gmail.com",
        "mobile": "3344556677",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "338",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99214, 92014",
        "proceduredesc": "E&M Level 4 - established patient - comprehensive exam, Comprehensive Eye Exam - established patient",
        "patientId": "068e6525-opto-b456-c789-d101112e1306",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    ImaSquint_ID_13: {
        "first_name": "Ima",
        "last_name": "Squint",
        "email": "ima.squint@gmail.com",
        "mobile": "4455667788",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "339",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "missed",
        "engage": true,
        "pozative": true,
        "procedurecode": "S0620",
        "proceduredesc": "Vision Examination - new patient",
        "patientId": "078e6525-opto-b456-c789-d101112e1307",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    IrisVision_ID_14: {
        "first_name": "Iris",
        "last_name": "Vision",
        "email": "iris.vision@gmail.com",
        "mobile": "5566778899",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "340",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "confirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99205",
        "proceduredesc": "E&M Level 5 - new patient - comprehensive exam",
        "patientId": "088e6525-opto-b456-c789-d101112e1308",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    ImaVision_ID_15: {
        "first_name": "Ima",
        "last_name": "Vision",
        "email": "joe@yahoo.com",
        "mobile": "6677889900",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "341",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "unconfirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "S0620",
        "proceduredesc": "Vision Examination - new patient",
        "patientId": "098e6525-opto-b456-c789-d101112e1309",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    OpheliaBright_ID_16: {
        "first_name": "Ophelia",
        "last_name": "Bright",
        "email": "ophelia.bright@gmail.com",
        "mobile": "7788990011",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "342",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        "procedurecode": "92004",
        "proceduredesc": "Comprehensive Eye Exam - new patient",
        "patientId": "108e6525-opto-b456-c789-d101112e1310",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    PatriciaSight_ID_17: {
        "first_name": "Patricia",
        "last_name": "Sight",
        "email": "patricia@yahoo.com",
        "mobile": "8899001122",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "343",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "missed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99202",
        "proceduredesc": "E&M Level 2 - new patient - focused extended problem",
        "patientId": "118e6525-opto-b456-c789-d101112e1311",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    PaulVision_ID_18: {
        "first_name": "Paul",
        "last_name": "Vision",
        "email": "paul.vision@gmail.com",
        "mobile": "9900112233",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "344",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "appointment confirmed",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        "procedurecode": "99203",
        "proceduredesc": "E&M Level 3 - new patient - detailed exam",
        "patientId": "128e6525-opto-b456-c789-d101112e1312",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    Peyton_L_Specter_ID_19: {
        "first_name": "Peyton L.",
        "last_name": "Specter",
        "email": "peyton.l.specter@gmail.com",
        "mobile": "1122334455",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "345",
        "appointment_status": "schedule",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "completed",
        "engage": true,
        "pozative": true,
        "procedurecode": "92014, 99214",
        "proceduredesc": "Comprehensive Eye Exam - established patient, E&M Level 4 - established patient - comprehensive exam",
        "patientId": "138e6525-opto-b456-c789-d101112e1313",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    SeymoreBlurry_ID_20: {
        "first_name": "Seymore",
        "last_name": "Blurry",
        "email": "seymore.blurry@gmail.com",
        "mobile": "3344556677",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "347",
        "appointment_status": "unconfirmed",
        "unschedule_status": "",
        "confirmed_status": "not called",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "appointmenttype": { "name": "New Patient Exam DR" },
        "location": locationObj,
        "finalstatus": "unconfirmed",
        "engage": true,
        "pozative": true,
        "procedurecode": "92004",
        "proceduredesc": "Comprehensive Eye Exam - new patient",
        "patientId": "158e6525-opto-b456-c789-d101112e1315",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": null,
        "closure_color": null,
        "groupId": null,
        "notes": ""
    },
    Block_ID_4: {
        "last_name": "",
        "email": "",
        "mobile": "",
        "comment": "",
        "homephone": "",
        "appt_ehr_id": "",
        "appointment_status": "block",
        "unschedule_status": "",
        "confirmed_status": "block",
        "is_ehr_completed": true,
        "operatory_starttime": 0,
        "operatory_endtime": 0,
        "provider": [],
        "appointmenttype": { "name": "Lunch" },
        "location": locationObj,
        "finalstatus": "block",
        "engage": true,
        "pozative": true,
        "procedurecode": "",
        "proceduredesc": "",
        "patientId": "",
        "appointmentlocationId": constantLocationData.austin.id,
        "appointmentlocationName": constantLocationData.austin.name,
        "closure_preference": "{\"closureType\":\"once\"}",
        "closure_color": "#072B40",
        "groupId": "",
        "notes": ""
    },
}

export const appointmentlocation_appientment_patient_true_opto_mock = {
    "status": true,
    "pozative": false,
    "engage": true,
    "data": [
        {
            ...apptsBase.BrittneyVision_ID_2,
            "patient_ehr_id": "opto-patient-ehr-id-1",
            "_id": "id-2",
            "$id": "id-2",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryOptoData.IMA_FOCUS],
            "provider": [constantOperatoryOptoData.IMA_FOCUS],
        },
        {
            ...apptsBase.IrisVision_ID_14,
            "patient_ehr_id": "opto-patient-ehr-id-2",
            "_id": "id-3",
            "$id": "id-3",
            "sharedSlotId": 'morningGroupB',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.PaulVision_ID_18,
            "patient_ehr_id": "opto-patient-ehr-id-3",
            "_id": "id-4",
            "$id": "id-4",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryOptoData.IMA_FOCUS],
            "provider": [constantOperatoryOptoData.IMA_FOCUS],
        },
        {
            ...apptsBase.OpheliaBright_ID_16,
            "patient_ehr_id": "opto-patient-ehr-id-4",
            "_id": "id-5",
            "$id": "id-5",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.Peyton_L_Specter_ID_1,
            "patient_ehr_id": "opto-patient-ehr-id-5",
            "_id": "id-6",
            "$id": "id-6",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.ImaSquint_ID_13,
            "patient_ehr_id": "opto-patient-ehr-id-6",
            "_id": "id-7",
            "$id": "id-7",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.ImaVision_ID_15,
            "patient_ehr_id": "opto-patient-ehr-id-7",
            "_id": "id-8",
            "$id": "id-8",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryOptoData.RAY_T_LIGHTER],
            "provider": [constantOperatoryOptoData.RAY_T_LIGHTER],
        },
        {
            ...apptsBase.ImaSeewell_ID_5,
            "patient_ehr_id": "opto-patient-ehr-id-8",
            "_id": "id-9",
            "$id": "id-9",
            "sharedSlotId": 'morningGroupB',
            "operatory": [constantOperatoryOptoData.RAY_T_LIGHTER],
            "provider": [constantOperatoryOptoData.RAY_T_LIGHTER],
        },
        {
            ...apptsBase.GailLFogg_ID_11,
            "patient_ehr_id": "opto-patient-ehr-id-9",
            "_id": "id-10",
            "$id": "id-10",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.GailLFogg_ID_11,
            "patient_ehr_id": "opto-patient-ehr-id-10",
            "_id": "id-11",
            "$id": "id-11",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.CeeVision_ID_3,
            "patient_ehr_id": "opto-patient-ehr-id-11",
            "_id": "id-12",
            "$id": "id-12",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.EllieOVision_ID_10,
            "patient_ehr_id": "opto-patient-ehr-id-12",
            "_id": "id-13",
            "$id": "id-13",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.Ray_N_Shine_ID_9,
            "patient_ehr_id": "opto-patient-ehr-id-13",
            "_id": "id-14",
            "$id": "id-14",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.SeymoreBlurry_ID_20,
            "patient_ehr_id": "opto-patient-ehr-id-14",
            "_id": "id-15",
            "$id": "id-15",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.CrystalClearview_ID_8,
            "patient_ehr_id": "opto-patient-ehr-id-15",
            "_id": "id-16",
            "$id": "id-16",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryOptoData.RAY_T_LIGHTER],
            "provider": [constantOperatoryOptoData.RAY_T_LIGHTER],
        },
        {
            ...apptsBase.ImaSquint_ID_13,
            "patient_ehr_id": "opto-patient-ehr-id-16",
            "_id": "id-17",
            "$id": "id-17",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.PatriciaSight_ID_17,
            "patient_ehr_id": "opto-patient-ehr-id-17",
            "_id": "id-18",
            "$id": "id-18",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.BrittneyVision_ID_6,
            "patient_ehr_id": "opto-patient-ehr-id-18",
            "_id": "id-19",
            "$id": "id-19",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.PaulVision_ID_18,
            "patient_ehr_id": "opto-patient-ehr-id-19",
            "_id": "id-20",
            "$id": "id-20",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryOptoData.IMA_FOCUS],
            "provider": [constantOperatoryOptoData.IMA_FOCUS],
        },
        {
            ...apptsBase.Ray_N_Shine_ID_9,
            "patient_ehr_id": "opto-patient-ehr-id-20",
            "_id": "id-21",
            "$id": "id-21",
            "sharedSlotId": 'morningGroupB',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.CeeVision_ID_7,
            "patient_ehr_id": "opto-patient-ehr-id-21",
            "_id": "id-22",
            "$id": "id-22",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryOptoData.IMA_FOCUS],
            "provider": [constantOperatoryOptoData.IMA_FOCUS],
        },
        {
            ...apptsBase.ImaSquint_ID_13,
            "patient_ehr_id": "opto-patient-ehr-id-22",
            "_id": "id-23",
            "$id": "id-23",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.ImaSquint_ID_13,
            "patient_ehr_id": "opto-patient-ehr-id-23",
            "_id": "id-24",
            "$id": "id-24",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.ImaVision_ID_15,
            "patient_ehr_id": "opto-patient-ehr-id-24",
            "_id": "id-25",
            "$id": "id-25",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryOptoData.RAY_T_LIGHTER],
            "provider": [constantOperatoryOptoData.RAY_T_LIGHTER],
        },
        {
            ...apptsBase.PatriciaSight_ID_17,
            "patient_ehr_id": "opto-patient-ehr-id-25",
            "_id": "id-26",
            "$id": "id-26",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.SeymoreBlurry_ID_20,
            "patient_ehr_id": "opto-patient-ehr-id-26",
            "_id": "id-27",
            "$id": "id-27",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryOptoData.I_C_WRIGHT],
            "provider": [constantOperatoryOptoData.I_C_WRIGHT],
        },
        {
            ...apptsBase.Peyton_L_Specter_ID_19,
            "patient_ehr_id": "opto-patient-ehr-id-27",
            "_id": "id-28",
            "$id": "id-28",
            "sharedSlotId": 'morningGroupC',
            "operatory": [constantOperatoryOptoData.RAY_T_LIGHTER],
            "provider": [constantOperatoryOptoData.RAY_T_LIGHTER],
        },
        {
            ...apptsBase.EllieOVision_ID_10,
            "patient_ehr_id": "opto-patient-ehr-id-28",
            "_id": "id-29",
            "$id": "id-29",
            "sharedSlotId": 'afternoonGroupA',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.IrisVision_ID_14,
            "patient_ehr_id": "opto-patient-ehr-id-29",
            "_id": "id-30",
            "$id": "id-30",
            "sharedSlotId": 'afternoonGroupB',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.CrystalClearview_ID_8,
            "patient_ehr_id": "opto-patient-ehr-id-30",
            "_id": "id-31",
            "$id": "id-31",
            "sharedSlotId": 'afternoonGroupC',
            "operatory": [constantOperatoryOptoData.RAY_T_LIGHTER],
            "provider": [constantOperatoryOptoData.RAY_T_LIGHTER],
        },
        {
            ...apptsBase.OpheliaBright_ID_16,
            "patient_ehr_id": "opto-patient-ehr-id-31",
            "_id": "id-32",
            "$id": "id-32",
            "sharedSlotId": 'morningGroupA',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.ImaSeewell_ID_12,
            "patient_ehr_id": "opto-patient-ehr-id-32",
            "_id": "id-33",
            "$id": "id-33",
            "sharedSlotId": 'morningGroupB',
            "operatory": [constantOperatoryOptoData.IMA_FOCUS],
            "provider": [constantOperatoryOptoData.IMA_FOCUS],
        },
        {
            ...apptsBase.Block_ID_4,
            "first_name": "Surgery or Emergency",
            "patient_ehr_id": "0",
            "_id": "id-1",
            "$id": "id-1",
            "sharedSlotId": 'Blockout1',
            "operatory": [constantOperatoryOptoData.AL_O_VEWELL],
            "provider": [constantOperatoryOptoData.AL_O_VEWELL],
        },
        {
            ...apptsBase.Block_ID_4,
            "first_name": "Scan Appointment",
            "patient_ehr_id": "0",
            "_id": "id-34",
            "$id": "id-34",
            "sharedSlotId": 'Blockout2',
            "operatory": [constantOperatoryOptoData.IMA_FOCUS],
            "provider": [constantOperatoryOptoData.IMA_FOCUS],
        },
    ],
    "loctimezone": locationTimezone,
    "error": null,
    "message": "Success",
    "offset": 330
};