const searchSMSLocation = {
    austin: { "$ref": "1e0d2d3b-c4ec-48e8-a0f5-fd327f7db948", "_id": "1e0d2d3b-c4ec-48e8-a0f5-fd327f7db948", "$id": "1e0d2d3b-c4ec-48e8-a0f5-fd327f7db948", },
    dallas: { "$ref": "22bffbc8-b255-4679-a5a9-7d2326ec2549", "_id": "22bffbc8-b255-4679-a5a9-7d2326ec2549", "$id": "22bffbc8-b255-4679-a5a9-7d2326ec2549", },
    houston: { "$ref": "869f9155-c174-4f94-b0e1-0ee8d84f3b2d", "_id": "869f9155-c174-4f94-b0e1-0ee8d84f3b2d", "$id": "869f9155-c174-4f94-b0e1-0ee8d84f3b2d", },
    default: { "$ref": "", "_id": "", "$id": "", },
}

const locationAllFields = {
    austin: {
        "locationId": searchSMSLocation.austin._id, "appointmentlocationId": searchSMSLocation.austin._id,
        "location": searchSMSLocation.austin, "appointmentlocation": searchSMSLocation.austin,
    },
    dallas: {
        "locationId": searchSMSLocation.dallas._id, "appointmentlocationId": searchSMSLocation.dallas._id,
        "location": searchSMSLocation.dallas, "appointmentlocation": searchSMSLocation.dallas,
    },
    houston: {
        "locationId": searchSMSLocation.houston._id, "appointmentlocationId": searchSMSLocation.houston._id,
        "location": searchSMSLocation.houston, "appointmentlocation": searchSMSLocation.houston,
    },
}

const searchSMSFullData = {
    dental: {
        austin: [
            {
                "smsId": "sms_id_mock_1",
                "text": "Missed call at 09:15 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "06dental-a123-b456-c789-d101112e1306",
                "patientFirstName": "Miley",
                "patientLastName": "Smiley",
                "patientMobile": "4693279399",
                "patientFullName": "Miley Smiley",
                "patientRFullName": "Smiley, Miley",
                "from_number": "8323646713",
                "to_number": "4693279399",
                "message_type": "outbound",
                "message_sub_type": "missed_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710502620000,
                "created_at": 1710502620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Miley",
                    "last_name": "Smiley",
                    "mobile": "4693279399",
                    "email": "miley.smiley@gmail.com",
                    "_id": "06dental-a123-b456-c789-d101112e1306",
                    "$id": "06dental-a123-b456-c789-d101112e1306",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_2",
                "text": "Inbound answered call at 10:20 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "08dental-a123-b456-c789-d101112e1308",
                "patientFirstName": "Annie",
                "patientLastName": "Steshia",
                "patientMobile": "5693279399",
                "patientFullName": "Annie Steshia",
                "patientRFullName": "Steshia, Annie",
                "from_number": "8323646713",
                "to_number": "5693279399",
                "message_type": "inbound",
                "message_sub_type": "inbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710505620000,
                "created_at": 1710505620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Annie",
                    "last_name": "Steshia",
                    "mobile": "5693279399",
                    "email": "annie.steshia@gmail.com",
                    "_id": "08dental-a123-b456-c789-d101112e1308",
                    "$id": "08dental-a123-b456-c789-d101112e1308",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_3",
                "text": "Outbound answered call at 03:45 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "09dental-a123-b456-c789-d101112e1309",
                "patientFirstName": "Sarah",
                "patientLastName": "Bellum",
                "patientMobile": "2321561581",
                "patientFullName": "Sarah Bellum",
                "patientRFullName": "Bellum, Sarah",
                "from_number": "8323646713",
                "to_number": "2321561581",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710512620000,
                "created_at": 1710512620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Sarah",
                    "last_name": "Bellum",
                    "mobile": "2321561581",
                    "email": "sarah.bellum@gmail.com",
                    "_id": "09dental-a123-b456-c789-d101112e1309",
                    "$id": "09dental-a123-b456-c789-d101112e1309",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_4",
                "text": "Missed call at 05:50 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "14dental-a123-b456-c789-d101112e1314",
                "patientFirstName": "Mandi",
                "patientLastName": "Bill",
                "patientMobile": "4693279391",
                "patientFullName": "Mandi Bill",
                "patientRFullName": "Bill, Mandi",
                "from_number": "8323646713",
                "to_number": "4693279391",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710522620000,
                "created_at": 1710522620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Mandi",
                    "last_name": "Bill",
                    "mobile": "4693279391",
                    "email": "mandi.bill@gmail.com",
                    "_id": "14dental-a123-b456-c789-d101112e1314",
                    "$id": "14dental-a123-b456-c789-d101112e1314",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            }
        ],
        dallas: [
            {
                "smsId": "sms_id_mock_5",
                "text": "Inbound answered call at 08:25 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "03dental-a123-b456-c789-d101112e1303",
                "patientFirstName": "Dan",
                "patientLastName": "Ture",
                "patientMobile": "8322958881",
                "patientFullName": "Dan Ture",
                "patientRFullName": "Ture, Dan",
                "from_number": "8323646713",
                "to_number": "8322958881",
                "message_type": "inbound",
                "message_sub_type": "inbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710532620000,
                "created_at": 1710532620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Dan",
                    "last_name": "Ture",
                    "mobile": "8322958881",
                    "email": "dan.ture@gmail.com",
                    "_id": "03dental-a123-b456-c789-d101112e1303",
                    "$id": "03dental-a123-b456-c789-d101112e1303",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_6",
                "text": "Missed call at 01:40 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "10dental-a123-b456-c789-d101112e1310",
                "patientFirstName": "Ernest",
                "patientLastName": "Flossy",
                "patientMobile": "8323464245",
                "patientFullName": "Ernest Flossy",
                "patientRFullName": "Flossy, Ernest",
                "from_number": "8323646713",
                "to_number": "8323464245",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710542620000,
                "created_at": 1710542620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Ernest",
                    "last_name": "Flossy",
                    "mobile": "8323464245",
                    "email": "ernest.flossy@gmail.com",
                    "_id": "10dental-a123-b456-c789-d101112e1310",
                    "$id": "10dental-a123-b456-c789-d101112e1310",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_7",
                "text": "Outbound answered call at 04:25 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "12dental-a123-b456-c789-d101112e1312",
                "patientFirstName": "Moe",
                "patientLastName": "Lars",
                "patientMobile": "8323646432",
                "patientFullName": "Moe Lars",
                "patientRFullName": "Lars, Moe",
                "from_number": "8323646713",
                "to_number": "8323646432",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710552620000,
                "created_at": 1710552620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Moe",
                    "last_name": "Lars",
                    "mobile": "8323646432",
                    "email": "moe.lars@gmail.com",
                    "_id": "12dental-a123-b456-c789-d101112e1312",
                    "$id": "12dental-a123-b456-c789-d101112e1312",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_8",
                "text": "Missed call at 07:05 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "15dental-a123-b456-c789-d101112e1315",
                "patientFirstName": "Ginger",
                "patientLastName": "Vitis",
                "patientMobile": "8323646680",
                "patientFullName": "Ginger Vitis",
                "patientRFullName": "Vitis, Ginger",
                "from_number": "8323646713",
                "to_number": "8323646680",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710562620000,
                "created_at": 1710562620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Ginger",
                    "last_name": "Vitis",
                    "mobile": "8323646680",
                    "email": "ginger.vitis@gmail.com",
                    "_id": "15dental-a123-b456-c789-d101112e1315",
                    "$id": "15dental-a123-b456-c789-d101112e1315",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            }
        ],
        houston: [
            {
                "smsId": "sms_id_mock_9",
                "text": "Outbound answered call at 09:55 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "01dental-a123-b456-c789-d101112e1301",
                "patientFirstName": "Ruth",
                "patientLastName": "Canal",
                "patientMobile": "7788990987",
                "patientFullName": "Ruth Canal",
                "patientRFullName": "Canal, Ruth",
                "from_number": "8323646713",
                "to_number": "7788990987",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710572620000,
                "created_at": 1710572620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Ruth",
                    "last_name": "Canal",
                    "mobile": "7788990987",
                    "email": "ruth.canal@gmail.com",
                    "_id": "01dental-a123-b456-c789-d101112e1301",
                    "$id": "01dental-a123-b456-c789-d101112e1301",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    // "profileimage": constantPatientData.dental.houston.patient_01_Ruth_Canal.profileimage
                },
                "unreadmessage_count": 0,
                // "patientProfileImage": constantPatientData.dental.houston.patient_01_Ruth_Canal.profileimage
            },
            {
                "smsId": "sms_id_mock_10",
                "text": "Inbound answered call at 11:45 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "02dental-a123-b456-c789-d101112e1302",
                "patientFirstName": "Eve",
                "patientLastName": "Namel",
                "patientMobile": "8325544754",
                "patientFullName": "Eve Namel",
                "patientRFullName": "Namel, Eve",
                "from_number": "8323646713",
                "to_number": "8325544754",
                "message_type": "inbound",
                "message_sub_type": "inbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710578620000,
                "created_at": 1710578620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Eve",
                    "last_name": "Namel",
                    "mobile": "8325544754",
                    "email": "eve.namel@gmail.com",
                    "_id": "02dental-a123-b456-c789-d101112e1302",
                    "$id": "02dental-a123-b456-c789-d101112e1302",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_11",
                "text": "Missed call at 03:15 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "05dental-a123-b456-c789-d101112e1305",
                "patientFirstName": "Pearl",
                "patientLastName": "White",
                "patientMobile": "8327894282",
                "patientFullName": "Pearl White",
                "patientRFullName": "White, Pearl",
                "from_number": "8323646713",
                "to_number": "8327894282",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710589620000,
                "created_at": 1710589620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Pearl",
                    "last_name": "White",
                    "mobile": "8327894282",
                    "email": "pearl.white@gmail.com",
                    "_id": "05dental-a123-b456-c789-d101112e1305",
                    "$id": "05dental-a123-b456-c789-d101112e1305",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_12",
                "text": "Outbound answered call at 06:30 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "04dental-a123-b456-c789-d101112e1304",
                "patientFirstName": "Perry",
                "patientLastName": "O'Dontist",
                "patientMobile": "8329551275",
                "patientFullName": "Perry O'Dontist",
                "patientRFullName": "O'Dontist Perry",
                "from_number": "8323646713",
                "to_number": "8329551275",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710601820000,
                "created_at": 1710601820000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Perry",
                    "last_name": "O'Dontist",
                    "mobile": "8329551275",
                    "email": "perry.o.Dontist@gmail.com",
                    "_id": "04dental-a123-b456-c789-d101112e1304",
                    "$id": "04dental-a123-b456-c789-d101112e1304",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_6",
                "text": "Missed call at 01:40 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "13dental-a123-b456-c789-d101112e1313",
                "patientFirstName": "Hal",
                "patientLastName": "Itosis",
                "patientMobile": "8323464245",
                "patientFullName": "Hal Itosis",
                "patientRFullName": "Itosis, Hal",
                "from_number": "8323646713",
                "to_number": "8323464245",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710542620000,
                "created_at": 1710542620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Hal",
                    "last_name": "Itosis",
                    "mobile": "8323464245",
                    "email": "hal.itosis@gmail.com",
                    "_id": "13dental-a123-b456-c789-d101112e1313",
                    "$id": "13dental-a123-b456-c789-d101112e1313",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            },
        ],
    },
    optometry: {
        austin: [
            {
                "smsId": "sms_id_mock_1",
                "text": "Missed call at 09:15 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "158e6525-opto-b456-c789-d101112e1315",
                "patientFirstName": "Seymore",
                "patientLastName": "Blurry",
                "patientMobile": "3644442722",
                "patientFullName": "Seymore Blurry",
                "patientRFullName": "Blurry, Seymore",
                "from_number": "8323646713",
                "to_number": "3644442722",
                "message_type": "outbound",
                "message_sub_type": "missed_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710502620000,
                "created_at": 1710502620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Seymore",
                    "last_name": "Blurry",
                    "mobile": "3644442722",
                    "email": "seymore.blurry@gmail.com",
                    "_id": "158e6525-opto-b456-c789-d101112e1315",
                    "$id": "158e6525-opto-b456-c789-d101112e1315",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_2",
                "text": "Inbound answered call at 10:20 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "028e6525-opto-b456-c789-d101112e1302",
                "patientFirstName": "Cee",
                "patientLastName": "Vision",
                "patientMobile": "3644442888",
                "patientFullName": "Cee Vision",
                "patientRFullName": "Vision, Cee",
                "from_number": "8323646713",
                "to_number": "3644442888",
                "message_type": "inbound",
                "message_sub_type": "inbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710505620000,
                "created_at": 1710505620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Cee",
                    "last_name": "Vision",
                    "mobile": "3644442888",
                    "email": "cee.vision@gmail.com",
                    "_id": "028e6525-opto-b456-c789-d101112e1302",
                    "$id": "028e6525-opto-b456-c789-d101112e1302",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_3",
                "text": "Outbound answered call at 03:45 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "118e6525-opto-b456-c789-d101112e1311",
                "patientFirstName": "Patricia",
                "patientLastName": "Sight",
                "patientMobile": "8322399798",
                "patientFullName": "Patricia Sight",
                "patientRFullName": "Sight, Patricia",
                "from_number": "8323646713",
                "to_number": "8322399798",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710512620000,
                "created_at": 1710512620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Patricia",
                    "last_name": "Sight",
                    "mobile": "8322399798",
                    "email": "patricia@yahoo.com",
                    "_id": "118e6525-opto-b456-c789-d101112e1311",
                    "$id": "118e6525-opto-b456-c789-d101112e1311",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_4",
                "text": "Missed call at 05:50 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "108e6525-opto-b456-c789-d101112e1310",
                "patientFirstName": "Ophelia",
                "patientLastName": "Bright",
                "patientMobile": "8322529998",
                "patientFullName": "Ophelia Bright",
                "patientRFullName": "Bright, Ophelia",
                "from_number": "8323646713",
                "to_number": "8322529998",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710522620000,
                "created_at": 1710522620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Ophelia",
                    "last_name": "Bright",
                    "mobile": "8322529998",
                    "email": "ophelia.bright@gmail.com",
                    "_id": "108e6525-opto-b456-c789-d101112e1310",
                    "$id": "108e6525-opto-b456-c789-d101112e1310",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            }
        ],
        dallas: [
            {
                "smsId": "sms_id_mock_5",
                "text": "Inbound answered call at 08:25 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "058e6525-opto-b456-c789-d101112e1305",
                "patientFirstName": "Gail L.",
                "patientLastName": "Fogg",
                "patientMobile": "8322958881",
                "patientFullName": "Gail L. Fogg",
                "patientRFullName": "Fogg, Gail L.",
                "from_number": "8323646713",
                "to_number": "8322958881",
                "message_type": "inbound",
                "message_sub_type": "inbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710532620000,
                "created_at": 1710532620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Gail L.",
                    "last_name": "Fogg",
                    "mobile": "8322958881",
                    "email": "gail.l.fogg@gmail.com",
                    "_id": "058e6525-opto-b456-c789-d101112e1305",
                    "$id": "058e6525-opto-b456-c789-d101112e1305",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_6",
                "text": "Missed call at 01:40 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "088e6525-opto-b456-c789-d101112e1308",
                "patientFirstName": "Iris",
                "patientLastName": "Vision",
                "patientMobile": "8323464245",
                "patientFullName": "Iris Vision",
                "patientRFullName": "Vision, Iris",
                "from_number": "8323646713",
                "to_number": "8323464245",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710542620000,
                "created_at": 1710542620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Iris",
                    "last_name": "Vision",
                    "mobile": "8323464245",
                    "email": "iris.vision@gmail.com",
                    "_id": "088e6525-opto-b456-c789-d101112e1308",
                    "$id": "088e6525-opto-b456-c789-d101112e1308",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_7",
                "text": "Outbound answered call at 04:25 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "098e6525-opto-b456-c789-d101112e1309",
                "patientFirstName": "Ima",
                "patientLastName": "Vision",
                "patientMobile": "8323646432",
                "patientFullName": "Ima Vision",
                "patientRFullName": "Vision, Ima",
                "from_number": "8323646713",
                "to_number": "8323646432",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710552620000,
                "created_at": 1710552620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Ima",
                    "last_name": "Vision",
                    "mobile": "8323646432",
                    "email": "joe@yahoo.com",
                    "_id": "098e6525-opto-b456-c789-d101112e1309",
                    "$id": "098e6525-opto-b456-c789-d101112e1309",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_8",
                "text": "Missed call at 07:05 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "128e6525-opto-b456-c789-d101112e1312",
                "patientFirstName": "Paul",
                "patientLastName": "Vision",
                "patientMobile": "8323646680",
                "patientFullName": "Paul Vision",
                "patientRFullName": "Vision, Paul",
                "from_number": "8323646713",
                "to_number": "8323646680",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710562620000,
                "created_at": 1710562620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Paul",
                    "last_name": "Vision",
                    "mobile": "8323646680",
                    "email": "paul.vision@gmail.com",
                    "_id": "128e6525-opto-b456-c789-d101112e1312",
                    "$id": "128e6525-opto-b456-c789-d101112e1312",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            }
        ],
        houston: [
            {
                "smsId": "sms_id_mock_9",
                "text": "Outbound answered call at 09:55 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "068e6525-opto-b456-c789-d101112e1306",
                "patientFirstName": "Ima",
                "patientLastName": "Seewell",
                "patientMobile": "8324768771",
                "patientFullName": "Ima Seewell",
                "patientRFullName": "Seewell, Ima",
                "from_number": "8323646713",
                "to_number": "8324768771",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710572620000,
                "created_at": 1710572620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Ima",
                    "last_name": "Seewell",
                    "mobile": "8324768771",
                    "email": "ima.seewell@gmail.com",
                    "_id": "068e6525-opto-b456-c789-d101112e1306",
                    "$id": "068e6525-opto-b456-c789-d101112e1306",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_10",
                "text": "Inbound answered call at 11:45 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "038e6525-opto-b456-c789-d101112e1303",
                "patientFirstName": "Crystal",
                "patientLastName": "Clearview",
                "patientMobile": "8325544754",
                "patientFullName": "Crystal Clearview",
                "patientRFullName": "Clearview, Crystal",
                "from_number": "8323646713",
                "to_number": "8325544754",
                "message_type": "inbound",
                "message_sub_type": "inbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710578620000,
                "created_at": 1710578620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Crystal",
                    "last_name": "Clearview",
                    "mobile": "8325544754",
                    "email": "crystal.clearview@gmail.com",
                    "_id": "038e6525-opto-b456-c789-d101112e1303",
                    "$id": "038e6525-opto-b456-c789-d101112e1303",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    // "profileimage": constantPatientData.dental.houston.patient_01_Ruth_Canal.profileimage
                },
                "unreadmessage_count": 0,
                // "patientProfileImage": constantPatientData.dental.houston.patient_01_Ruth_Canal.profileimage
            },
            {
                "smsId": "sms_id_mock_11",
                "text": "Missed call at 03:15 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "078e6525-opto-b456-c789-d101112e1307",
                "patientFirstName": "Ima",
                "patientLastName": "Squint",
                "patientMobile": "8327894282",
                "patientFullName": "Ima Squint",
                "patientRFullName": "Squint, Ima",
                "from_number": "8323646713",
                "to_number": "8327894282",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710589620000,
                "created_at": 1710589620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Ima",
                    "last_name": "Squint",
                    "mobile": "8327894282",
                    "email": "ima.squint@gmail.com",
                    "_id": "078e6525-opto-b456-c789-d101112e1307",
                    "$id": "078e6525-opto-b456-c789-d101112e1307",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_12",
                "text": "Outbound answered call at 06:30 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "148e6525-opto-b456-c789-d101112e1314",
                "patientFirstName": "Ray N.",
                "patientLastName": "Shine",
                "patientMobile": "8329551275",
                "patientFullName": "Ray N. Shine",
                "patientRFullName": "Shine, Ray N.",
                "from_number": "8323646713",
                "to_number": "8329551275",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710601820000,
                "created_at": 1710601820000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Ray N.",
                    "last_name": "Shine",
                    "mobile": "8329551275",
                    "email": "ray.n.shine@gmail.com",
                    "_id": "148e6525-opto-b456-c789-d101112e1314",
                    "$id": "148e6525-opto-b456-c789-d101112e1314",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            }
        ],
    },
    chiropractor: {
        austin: [
            {
                "smsId": "sms_id_mock_1",
                "text": "Missed call at 09:15 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "06chirop-a123-b456-c789-d101112e1306",
                "patientFirstName": "Flex",
                "patientLastName": "Spine",
                "patientMobile": "3644442722",
                "patientFullName": "Flex Spine",
                "patientRFullName": "Spine, Flex",
                "from_number": "8323646713",
                "to_number": "3644442722",
                "message_type": "outbound",
                "message_sub_type": "missed_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710502620000,
                "created_at": 1710502620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Flex",
                    "last_name": "Spine",
                    "mobile": "3644442722",
                    "email": "flex.spine@gmail.com",
                    "_id": "06chirop-a123-b456-c789-d101112e1306",
                    "$id": "06chirop-a123-b456-c789-d101112e1306",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_2",
                "text": "Inbound answered call at 10:20 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "12chirop-a123-b456-c789-d101112e1312",
                "patientFirstName": "Rhea",
                "patientLastName": "Adjust",
                "patientMobile": "3644442888",
                "patientFullName": "Rhea Adjust",
                "patientRFullName": "Adjust, Rhea",
                "from_number": "8323646713",
                "to_number": "3644442888",
                "message_type": "inbound",
                "message_sub_type": "inbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710505620000,
                "created_at": 1710505620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Rhea",
                    "last_name": "Adjust",
                    "mobile": "3644442888",
                    "email": "rhea.adjust@gmail.com",
                    "_id": "12chirop-a123-b456-c789-d101112e1312",
                    "$id": "12chirop-a123-b456-c789-d101112e1312",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_3",
                "text": "Outbound answered call at 03:45 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "11chirop-a123-b456-c789-d101112e1311",
                "patientFirstName": "Paige",
                "patientLastName": "Turner",
                "patientMobile": "8322399798",
                "patientFullName": "Paige Turner",
                "patientRFullName": "Turner, Paige",
                "from_number": "8323646713",
                "to_number": "8322399798",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710512620000,
                "created_at": 1710512620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Paige",
                    "last_name": "Turner",
                    "mobile": "8322399798",
                    "email": "paige.turner@gmail.com",
                    "_id": "11chirop-a123-b456-c789-d101112e1311",
                    "$id": "11chirop-a123-b456-c789-d101112e1311",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_4",
                "text": "Missed call at 05:50 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "13chirop-a123-b456-c789-d101112e1313",
                "patientFirstName": "Rolland",
                "patientLastName": "Over",
                "patientMobile": "8322529998",
                "patientFullName": "Rolland Over",
                "patientRFullName": "Over, Rolland",
                "from_number": "8323646713",
                "to_number": "8322529998",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710522620000,
                "created_at": 1710522620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.austin,
                "patient": {
                    "first_name": "Rolland",
                    "last_name": "Over",
                    "mobile": "8322529998",
                    "email": "rolland.over@gmail.com",
                    "_id": "13chirop-a123-b456-c789-d101112e1313",
                    "$id": "13chirop-a123-b456-c789-d101112e1313",
                    "location": searchSMSLocation.austin,
                    "appointmentlocation": searchSMSLocation.austin,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            }
        ],
        dallas: [
            {
                "smsId": "sms_id_mock_5",
                "text": "Inbound answered call at 08:25 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "04chirop-a123-b456-c789-d101112e1304",
                "patientFirstName": "Bone",
                "patientLastName": "Care",
                "patientMobile": "8322958881",
                "patientFullName": "Bone Care",
                "patientRFullName": "Care, Bone",
                "from_number": "8323646713",
                "to_number": "8322958881",
                "message_type": "inbound",
                "message_sub_type": "inbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710532620000,
                "created_at": 1710532620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Bone",
                    "last_name": "Care",
                    "mobile": "8322958881",
                    "email": "bone.care@gmail.com",
                    "_id": "04chirop-a123-b456-c789-d101112e1304",
                    "$id": "04chirop-a123-b456-c789-d101112e1304",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_6",
                "text": "Missed call at 01:40 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "05chirop-a123-b456-c789-d101112e1305",
                "patientFirstName": "Chiro",
                "patientLastName": "Spondylus",
                "patientMobile": "8323464245",
                "patientFullName": "Chiro Spondylus",
                "patientRFullName": "Spondylus, Chiro",
                "from_number": "8323646713",
                "to_number": "8323464245",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710542620000,
                "created_at": 1710542620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Chiro",
                    "last_name": "Spondylus",
                    "mobile": "8323464245",
                    "email": "chiro.spondylus@gmail.com",
                    "_id": "05chirop-a123-b456-c789-d101112e1305",
                    "$id": "05chirop-a123-b456-c789-d101112e1305",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_7",
                "text": "Outbound answered call at 04:25 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "10chirop-a123-b456-c789-d101112e1310",
                "patientFirstName": "Leslie",
                "patientLastName": "Backus",
                "patientMobile": "8323646432",
                "patientFullName": "Leslie Backus",
                "patientRFullName": "Backus, Leslie",
                "from_number": "8323646713",
                "to_number": "8323646432",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710552620000,
                "created_at": 1710552620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Leslie",
                    "last_name": "Backus",
                    "mobile": "8323646432",
                    "email": "leslie.backus@gmail.com",
                    "_id": "10chirop-a123-b456-c789-d101112e1310",
                    "$id": "10chirop-a123-b456-c789-d101112e1310",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_8",
                "text": "Missed call at 07:05 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "14chirop-a123-b456-c789-d101112e1314",
                "patientFirstName": "Timberly",
                "patientLastName": "Neck",
                "patientMobile": "8323646680",
                "patientFullName": "Timberly Neck",
                "patientRFullName": "Neck, Timberly",
                "from_number": "8323646713",
                "to_number": "8323646680",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1755687840000,
                "created_at": 1755687840000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.dallas,
                "patient": {
                    "first_name": "Timberly",
                    "last_name": "Neck",
                    "mobile": "8323646680",
                    "email": "timberly.neck@gmail.com",
                    "_id": "14chirop-a123-b456-c789-d101112e1314",
                    "$id": "14chirop-a123-b456-c789-d101112e1314",
                    "location": searchSMSLocation.dallas,
                    "appointmentlocation": searchSMSLocation.dallas,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            }
        ],
        houston: [
            {
                "smsId": "sms_id_mock_9",
                "text": "Outbound answered call at 09:55 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "01chirop-a123-b456-c789-d101112e1301",
                "patientFirstName": "Ally",
                "patientLastName": "Vertebrae",
                "patientMobile": "8324768771",
                "patientFullName": "Ally Vertebrae",
                "patientRFullName": "Vertebrae, Ally",
                "from_number": "8323646713",
                "to_number": "8324768771",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710572620000,
                "created_at": 1710572620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Ally",
                    "last_name": "Vertebrae",
                    "mobile": "8324768771",
                    "email": "ally.vertebrae@gmail.com",
                    "_id": "01chirop-a123-b456-c789-d101112e1301",
                    "$id": "01chirop-a123-b456-c789-d101112e1301",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_10",
                "text": "Inbound answered call at 11:45 AM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "02chirop-a123-b456-c789-d101112e1302",
                "patientFirstName": "Anita",
                "patientLastName": "Crack",
                "patientMobile": "8325544754",
                "patientFullName": "Anita Crack",
                "patientRFullName": "Crack, Anita",
                "from_number": "8323646713",
                "to_number": "8325544754",
                "message_type": "inbound",
                "message_sub_type": "inbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710578620000,
                "created_at": 1710578620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Anita",
                    "last_name": "Crack",
                    "mobile": "8325544754",
                    "email": "anita.crack@gmail.com",
                    "_id": "02chirop-a123-b456-c789-d101112e1302",
                    "$id": "02chirop-a123-b456-c789-d101112e1302",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    // "profileimage": constantPatientData.dental.houston.patient_01_Ruth_Canal.profileimage
                },
                "unreadmessage_count": 0,
                // "patientProfileImage": constantPatientData.dental.houston.patient_01_Ruth_Canal.profileimage
            },
            {
                "smsId": "sms_id_mock_11",
                "text": "Missed call at 03:15 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "03chirop-a123-b456-c789-d101112e1303",
                "patientFirstName": "Bend E.",
                "patientLastName": "Back",
                "patientMobile": "8327894282",
                "patientFullName": "Bend E. Back",
                "patientRFullName": "Back, Bend E.",
                "from_number": "8323646713",
                "to_number": "8327894282",
                "message_type": "call",
                "message_sub_type": "missed_call",
                "is_message_read": false,
                "is_manually_message_unread": false,
                "message_direction": "inbound",
                "message_date_time": 1710589620000,
                "created_at": 1710589620000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Bend E.",
                    "last_name": "Back",
                    "mobile": "8327894282",
                    "email": "bend.e.back@gmail.com",
                    "_id": "03chirop-a123-b456-c789-d101112e1303",
                    "$id": "03chirop-a123-b456-c789-d101112e1303",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 1,
                "patientProfileImage": ""
            },
            {
                "smsId": "sms_id_mock_12",
                "text": "Outbound answered call at 06:30 PM",
                "app_alias": "call",
                "messageUUID": "messageUuid",
                "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
                "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
                "patientId": "15chirop-a123-b456-c789-d101112e1315",
                "patientFirstName": "Tori",
                "patientLastName": "Spinal",
                "patientMobile": "8329551275",
                "patientFullName": "Tori Spinal",
                "patientRFullName": "Spinal, Tori",
                "from_number": "8323646713",
                "to_number": "8329551275",
                "message_type": "outbound",
                "message_sub_type": "outbound_answer_call",
                "is_message_read": true,
                "is_manually_message_unread": false,
                "message_direction": "outbound",
                "message_date_time": 1710601820000,
                "created_at": 1710601820000,
                "is_active": true,
                "is_deleted": false,
                ...locationAllFields.houston,
                "patient": {
                    "first_name": "Tori",
                    "last_name": "Spinal",
                    "mobile": "8329551275",
                    "email": "tori.spinal@gmail.com",
                    "_id": "15chirop-a123-b456-c789-d101112e1315",
                    "$id": "15chirop-a123-b456-c789-d101112e1315",
                    "location": searchSMSLocation.houston,
                    "appointmentlocation": searchSMSLocation.houston,
                    "profileimage": ""
                },
                "unreadmessage_count": 0,
                "patientProfileImage": ""
            }
        ],
    },
    default: [
        {
            "smsId": "sms_id_mock_default",
            "text": "Missed call at 04:03 PM",
            "app_alias": "call",
            "messageUUID": "messageUuid",
            "organizationId": "a9d05186-74bd-4249-ac2b-a35f7534935a",
            "locationId": searchSMSLocation.default._id,
            "appointmentlocationId": searchSMSLocation.default._id,
            "tracking_number_numberId": "55dcadc7-50db-4a8f-acf5-2b2a9fc4f446",
            "patientId": null,
            "patientFirstName": null,
            "patientLastName": null,
            "patientMobile": "4532770987",
            "patientFullName": null,
            "patientRFullName": null,
            "from_number": "8323646713",
            "to_number": "4532770987",
            "message_type": "call",
            "message_sub_type": "missed_call",
            "is_message_read": true,
            "is_manually_message_unread": false,
            "message_direction": "inbound",
            "message_date_time": 1241980980000,
            "created_at": 1241980980000,
            "is_active": true,
            "is_deleted": false,
            "location": searchSMSLocation.default,
            "appointmentlocation": searchSMSLocation.default,
            "patient": {
                "first_name": null,
                "last_name": null,
                "mobile": "4532770987",
                "_id": null,
                "$id": null,
                "location": searchSMSLocation.default,
                "appointmentlocation": searchSMSLocation.default,
                "profileimage": ""
            },
            "unreadmessage_count": 0,
            "patientProfileImage": ""
        }
    ]
}

export const searchSMSDataMock = {
    dental: {
        allCalls: {
            all: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    ...searchSMSFullData.dental.austin,
                    ...searchSMSFullData.dental.dallas,
                    ...searchSMSFullData.dental.houston,
                    ...searchSMSFullData.default,
                ],
                "totalLength": searchSMSFullData.dental.austin.length + searchSMSFullData.dental.dallas.length + searchSMSFullData.dental.houston.length + searchSMSFullData.default.length
            },
            austin: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    ...searchSMSFullData.dental.austin,
                    ...searchSMSFullData.default,
                ],
                "totalLength": searchSMSFullData.dental.austin.length + searchSMSFullData.default.length
            },
            dallas: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    ...searchSMSFullData.dental.dallas,
                    ...searchSMSFullData.default,
                ],
                "totalLength": searchSMSFullData.dental.dallas.length + searchSMSFullData.default.length
            },
            houston: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    ...searchSMSFullData.dental.houston,
                    ...searchSMSFullData.default,
                ],
                "totalLength": searchSMSFullData.dental.houston.length + searchSMSFullData.default.length
            },
        },
        missedCalls: {
            all: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.dental.austin,
                    searchSMSFullData.dental.austin,
                    searchSMSFullData.dental.dallas,
                    searchSMSFullData.dental.dallas,
                    searchSMSFullData.dental.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 6
            },
            austin: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.dental.austin,
                    searchSMSFullData.dental.austin,
                    searchSMSFullData.default,
                ],
                "totalLength": 3
            },
            dallas: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.dental.dallas,
                    searchSMSFullData.dental.dallas,
                    searchSMSFullData.default,
                ],
                "totalLength": 3
            },
            houston: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    // searchSMSFullData.dental.dallas,
                    searchSMSFullData.dental.houston,
                    searchSMSFullData.dental.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 2
            },
        },
    },
    optometry: {
        allCalls: {
            all: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 13
            },
            austin: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.default,
                ],
                "totalLength": 5
            },
            dallas: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.default,
                ],
                "totalLength": 5
            },
            houston: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 5
            },
        },
        missedCalls: {
            all: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 6
            },
            austin: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.optometry.austin,
                    searchSMSFullData.default,
                ],
                "totalLength": 3
            },
            dallas: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.optometry.dallas,
                    searchSMSFullData.default,
                ],
                "totalLength": 3
            },
            houston: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.optometry.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 2
            },
        },
    },
    chiropractor: {
        allCalls: {
            all: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 13
            },
            austin: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.default,
                ],
                "totalLength": 5
            },
            dallas: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.default,
                ],
                "totalLength": 5
            },
            houston: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 5
            },
        },
        missedCalls: {
            all: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 6
            },
            austin: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.chiropractor.austin,
                    searchSMSFullData.default,
                ],
                "totalLength": 3
            },
            dallas: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.chiropractor.dallas,
                    searchSMSFullData.default,
                ],
                "totalLength": 3
            },
            houston: {
                "status": true,
                "message": "Sms Record found!",
                "error": null,
                "data": [
                    searchSMSFullData.chiropractor.houston,
                    searchSMSFullData.default,
                ],
                "totalLength": 2
            },
        },
    },
}